### ISSUE TITLE
Ubuntu 18.04 LXC, not starting

### ISSUE THREAD

**Issue by ameeno** [MysticRyuujin/guac-install#101]
nmap does not show port 8080 as being open , cant see it actually launching, during install, the only error i see is 

guacd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable guacd
ln: target '/usr/lib/x86_64-linux-gnu/freerdp/' is not a directory: No such file or directory
Restarting tomcat...

It seems that freerdp-dev does not exist?

**Comment by MysticRyuujin** [comment]
Can you try adding `libfreerdp-plugins-standard` or running `apt -y install libfreerdp-plugins-standard` before running the script?

**Comment by ameeno** [comment]
Hello, it was a fresh Ubuntu, unfortunately it wasn't working. I switched to the docker install.

Whilst much heavier on resources, it does work.
 Guac tomcat simply does not stay open.

**Comment by MysticRyuujin** [comment]
I figured out why that error is present but it doesn't affect anything as far as I can tell.

**Comment by MysticRyuujin** [comment]
If you'd like to try the latest commit on the master that'd be helpful.

**Comment by ameeno** [comment]
Sure thing, I'll fire up an lxc and give it a test on 18.04

**Comment by MysticRyuujin** [comment]
I'm closing this, feel free to re-open if you need to
