### ISSUE TITLE
Ubuntu 18.04.4 TLS (with desktop) tomcat UI up but no connection to guac

### ISSUE THREAD

**Issue by brettferrell** [MysticRyuujin/guac-install#102]
I admit I'm a bit of a noob, but I have a clean/new install of 18.04 on Proxmox, the script runs to completion fine, the web UI is up, but it always bombs out when I try to login.  I'm not clear on where the log is.  I see guacamole.war in /etc/guacamole.

script output
```
bferrell@gaucamole:~$ sudo ./guac-install.sh
(!) Would you like to install TOTP? (y/N): y
(!) Would you like to install Duo (configuration values must be set after install in guacamole.properties)? (y/N): y
(!) Would you like to install MySQL? (Y/n): y

Enter a MySQL ROOT Password: 
Confirm MySQL ROOT Password: 

Enter a Guacamole User Database Password: 
Confirm Guacamole User Database Password: 

Installing dependencies. This might take a few minutes...
OK
Downloading Files...
guacamole-server-1. 100%[===================>]   1002K  3.02MB/s    in 0.3s    
Downloaded guacamole-server-1.1.0.tar.gz
guacamole-1.1.0.war 100%[===================>]   9.08M  7.80MB/s    in 1.2s    
Downloaded guacamole-1.1.0.war
guacamole-auth-jdbc 100%[===================>]  12.99M  5.77MB/s    in 2.3s    
Downloaded guacamole-auth-jdbc-1.1.0.tar.gz
guacamole-auth-totp 100%[===================>]   3.67M   608KB/s    in 7.1s    
Downloaded guacamole-auth-totp-1.1.0.tar.gz
Downloading complete.
guacamole-auth-duo- 100%[===================>] 687.66K  --.-KB/s    in 0.1s    
Downloaded guacamole-auth-duo-1.1.0.tar.gz
Downloading complete.
Building Guacamole with GCC 7.4.0 
Configuring. This might take a minute...
OK
Running Make. This might take a few minutes...
OK
Running Make Install...
OK
guacd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable guacd
ln: target '/usr/lib/x86_64-linux-gnu/freerdp/' is not a directory: No such file or directory
Duo is installed, it will need to be configured via guacamole.properties!
Restarting tomcat...
OK
Adding db tables...
OK
Starting guacamole...
Cleanup install files...
OK
Installation Complete
http://localhost:8080/guacamole/
Default login guacadmin:guacadmin
Be sure to change the password.
```

**Comment by MysticRyuujin** [comment]
Hey @SoulSeekkor did you test if you can install both MFA options at the same time? User selected Y on both...

**Comment by brettferrell** [comment]
Yea, I'm an idiot... that seems to be the issue.  Double checking, but I think it's letting me in.  Sorry.  :-(

**Comment by brettferrell** [comment]
as an aside, is there an easy way to check on the RDP error?  I'd like to get that working as well.

> Executing: /lib/systemd/systemd-sysv-install enable guacd
> ln: target '/usr/lib/x86_64-linux-gnu/freerdp/' is not a directory: No such file or directory

**Comment by brettferrell** [comment]
if I just get the right RDP library installed, will it work or do I need to recompile the client or server?  THanks again for the quick response, BTW.

**Comment by brettferrell** [comment]
Ok, I did rerun with one TOTP selected, and can configure and connect to Linux hosts. I can configure RDP hosts, but cannot connect to them (error: The remote desktop server is currently unreachable. If the problem persists, please notify your system administrator, or check your system logs.)

**Comment by MysticRyuujin** [comment]
Can you try adding `libfreerdp-plugins-standard` or running `apt -y install libfreerdp-plugins-standard` before running the script?

**Comment by brettferrell** [comment]
OK, after some conversation over on the Guca user community, changing my Win10 VM to disable WDDM allows me to connect to my Win10 RDP VM.   I have confirmed the script works for 1.0 and 1.1 on 18.04 if I disable WDDM on the target Win10 system.

**Comment by SoulSeekkor** [comment]
@MysticRyuujin Sorry for the late response, yes it works if you have both (super secure! lol) enabled.  I'd like to see how much work it would take to use the latest freerdp2 code as the Ubuntu one is pretty old and I've noticed some issues (mostly minor).  The most frustrating though is if I right-click on the start menu in a Server 2012 R2 machine I get disconnected from that machine.

**Comment by MysticRyuujin** [comment]
I also noticed that issue haha. The Guacamole 1.2.0 milestone in their JIRA is pretty active. I don't know if its going to be another year before they release or what, but I'm open to patches...

I disabled the ability to install both in the script 😁

**Comment by SoulSeekkor** [comment]
Okay :)  Yeah I may take a look to see if there's a good milestone a point to grab for maybe making freerdp2 from source during the install (optionally of course), didn't know there was a 1.2 milestone for Guac already, I'll have to take a look!
