### ISSUE TITLE
Script works well. How to manage Active Directory users

### ISSUE THREAD

**Issue by tahaboooo** [MysticRyuujin/guac-install#103]
Hello, 

I'm a noob in Guacamole ! Authentication works good with  Active Directory on a Windows Server 2012.  but i don't know how to manage users and give them access to Servers. Any help is appreciated. 

Thank you

Taha

**Comment by Tacioandrade** [comment]
Apparently this script doesn't have LDAP support, the only one I found with this support is one using CentOS as a base: https://github.com/Zer0CoolX/guacamole-install-rhel
A pity because I always work with Ubuntu or Debian and I would like to test LDAP on Guacamole, apparently I will have to test it with CentOS. =(

**Comment by tahaboooo** [comment]
It worked with me finally. You just have to put guacamole ldap config in guacamole proporties file and create an active directory user with "guacadmin" name.( Guacamole administrator )

**Comment by Tacioandrade** [comment]
Please describe the step by step better! You cannot understand what you really did! Which file did you download and play in which location?
If you can describe it better then I would appreciate it!

**Comment by tahaboooo** [comment]
I will do it first thing tomorrow morning :)

**Comment by tahaboooo** [comment]
here's my guacamole.properties file : 

ysql-hostname: localhost
mysql-port: 3306
mysql-database: guacamole_db
mysql-username: guacamole_user
mysql-password: root
# duo-api-hostname:
# duo-integration-key:
# duo-secret-key:
# duo-application-key:




# LDAP properties
ldap-hostname:           xxxxx.xxxx.xxxx.xx
ldap-port:               389
ldap-user-base-dn:       CN=xxx,DC=xxx,DC=xxx,DC=xxx
ldap-username-attribute: CN

 so all what you have to do is put the right values for these attributes. Then add a user in Active Directory called "guacadmin". 

Hope it'll help. 

Taha

**Comment by Tacioandrade** [comment]
> here's my guacamole.properties file :
> 
> ```
> mysql-hostname: localhost
> mysql-port: 3306
> mysql-database: guacamole_db
> mysql-username: guacamole_user
> mysql-password: root
> # duo-api-hostname:
> # duo-integration-key:
> # duo-secret-key:
> # duo-application-key:
> 
> # LDAP properties
> ldap-hostname:           xxxxx.xxxx.xxxx.xx
> ldap-port:               389
> ldap-user-base-dn:       CN=xxx,DC=xxx,DC=xxx,DC=xxx
> ldap-username-attribute: CN
> ```
> 
> so all what you have to do is put the right values for these attributes. Then add a user in Active Directory called "guacadmin".
> 
> Hope it'll help.
> 
> Taha

And the .jar file is thrown in the tomcat folder or where?

**Comment by tahaboooo** [comment]
i didn't modify anything else the script donwloads the jar file and put in the right place.
