### ISSUE TITLE
Ran Upgrade script, still running 1.0.0

### ISSUE THREAD

**Issue by robrff** [MysticRyuujin/guac-install#106]
I'm running Guacamole on Ubuntu 18.04 and ran the ./guac-upgrade.sh script, ran with no errors, and after everything restarts, and I get to the login page, I'm still showing 1.0.0, so I'm wondering what I may have done wrong? Thanks!

**Comment by MysticRyuujin** [comment]
Did you clear your browser cache?

**Comment by robrff** [comment]
Now I feel like a real idiot...........

But thank you, because your script is awesome!
