### ISSUE TITLE
Feature Request: Script support for MS SQL server

### ISSUE THREAD

**Issue by Marcus-James-Adams** [MysticRyuujin/guac-install#109]
I'm looking at running Guacamole against MS SQL server in Azure as they have now announced https://docs.microsoft.com/en-us/azure/sql-database/sql-database-serverless which bills by the second.

It would be nice if the script could also support using that as a setup option since Guacamole it self support's it.

**Comment by MysticRyuujin** [comment]
There's very little chance that I'll build that into this script directly. However, setting it up probably wouldn't be that hard. I imagine you need to simply say "N" when asked if you want to install MySQL. It then prompts you for the remote SQL server information.

I haven't looked into it though, is there a different connector? Do you need additional parameters?

**Comment by MysticRyuujin** [comment]
So I looked at it does indeed require a different connector 😞

`guacamole-auth-jdbc-sqlserver-1.1.0.jar`

> The SQL Server JDBC driver is not included with the extension. You must obtain the JDBC driver .jar yourself and place it in the directory.

So we'd have to deal with that too (which we do deal with for MySQL now) but Microsoft doesn't seem to make it easy to download the latest version from the series of links I have to go through to get the JDBC drivers...

We'd likely have to build a switch into the logic to ask the user which database type they want to connect to. That's quite  bit of work 😞 

In all likelihood it would make sense to break up the install script into two parts: one that deals with the database authentication stuff, and one that installs guac, but idk if I want to maintain that lol
