### ISSUE TITLE
RDP not working after fresh install

### ISSUE THREAD

**Issue by stinkcheese** [MysticRyuujin/guac-install#112]
I had to perform a fresh install the other day after some issues with an old TOTP setup and getting a new phone.
I entered in all the same settings i always use for RDP but i wont connect anymore after installing 1.1.0.
It looks like it connects to the machine as i can see the cursor, but then it disconnects right away. 
Any suggestions or know issues with the RDP element?

**Comment by drewkopp** [comment]
having same issue - RDP doesnt work on fresh install. Thought this might be related to the OS I installed on (Ubuntu 18.04) so I tried this script on 16.04 - unable to install packages

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package freerdp2-dev
E: Unable to locate package freerdp2-x11

**Comment by drewkopp** [comment]
can confirm that this is something in 1.1.0 that's broken. I just used the c2be296 on Oct 28, 2019 release of guac-install.sh which installs 1.0.0 fine on 16.04 and connections work again

**Comment by MysticRyuujin** [comment]
There is a docker script however, it's been a while since anyone has given feedback on it and it doesn't support the MFA stuff. Hopefully the Ubuntu package gets updated soon.

**Comment by graham00** [comment]
This is the same issue as:

https://github.com/MysticRyuujin/guac-install/issues/118

Just posted the Ubuntu-specific commands to recompile freerdp + guacamole from source to resolve it.

...was tempted to go with docker myself when I realized what was happening with the guacd segfault, but I figure I've got enough to worry about with all this covid stuff, without trying to wrap my head around learning docker too! :)

**Comment by MysticRyuujin** [comment]
Try this as a fix:

```
sudo add-apt-repository ppa:remmina-ppa-team/freerdp-daily
sudo apt-get update
sudo apt-get install freerdp2-dev freerdp2-x11
```
