### ISSUE TITLE
Script ignores some switches

### ISSUE THREAD

**Issue by LeBrad** [MysticRyuujin/guac-install#113]
The script will always interactively ask for the MySQL root password and the Guacamole user database password even if they are provided using switches on the command line. 

In the code, the switches successfully set their respective variables, mysqlRootPwd and guacPwd, but they are then ignored.

Please make the script usable non-interactively.

**Comment by MysticRyuujin** [comment]
I will take a look this weekend. It used to work that way, but perhaps it was broken.
