### ISSUE TITLE
Upgrade from 8.0.32 to 8.5.51

### ISSUE THREAD

**Issue by sebastianhueter** [MysticRyuujin/guac-install#120]
Hello,

after upgrading from Guacamole 1.0.0 to 1.1.0, I am trying to upgrade the tomcat version through overwriting the lib-folder /usr/share/tomcat8/lib/ with the one from http://apache.mirror.rafal.ca/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz and I am getting the error: "The origin server did not find a current representation for the target resource or is not willing to disclose that one exists." in browser...

and in catalina.out:
Cannot instantiate an authenticator of class [org.apache.catalina.authenticator.NonLoginAuthenticator]

Can you please help me upgrading tomcat to 8.5.51 while staying persistent and compatible with the next guac-upgrade.sh? ;-) Thank you

**Comment by MysticRyuujin** [comment]
I'm not familiar with the upgrade process to be honest. I would think it would be easier to just move the guac specific stuff out of the current tomcat folder, remove tomcat entirely, then reinstall with the new tomcat, then move the files back.

I also recommend running guac on a VM or something so you can just wipe it and start fresh if needed 😄
