### ISSUE TITLE
AD Authentication not running

### ISSUE THREAD

**Issue by nachoescalada** [MysticRyuujin/guac-install#121]
Hi,
After fresh install, I can't get LDAP integration working.
The LDAP extension is in the right folder and guacamole.properties is configured, but AD users are not shown...

**Comment by fone** [comment]
I'm having the same issue. Did you figure out what the problem was?

**Comment by iMrSquare** [comment]
Hi,
Once you have the LDAP extension in your folder you must configure the guacamole.properties with the following data. *edit what is necessary.

```
#LDAP properties
#Server connection
ldap-hostname: 192.168.1.200
ldap-port: 389
ldap-encryption-method: none
#User organizational unit
ldap-user-base-dn: OU=Users,DC=domain,DC=local
#Search attribute
ldap-username-attribute: sAMAccountName
#Users to login to check users
ldap-search-bind-dn: CN=user, OU=Users,DC=domain,DC=local
ldap-search-bind-password: passwd
#Search only filters up to 200 users (*not necessary by default)
ldap-user-search-filter: (objectClass=user)(!(objectCategory=computer))
ldap-max-search-results: 200
```

For the user to be created in guacamole, it must be in ldap-user-base-dn: we create it with another password than the domain one. With guacadmin we give all the permissions to the user and then we authenticate with the data of the domain that user and his password of the domain and the users will appear.

The ldap-search-bind-dn user: it only serves to find the users not to add them to guacamole.

I hope it works.
