### ISSUE TITLE
VNC Disconnects

### ISSUE THREAD

**Issue by robetus** [MysticRyuujin/guac-install#124]
Fresh install, fantastic script but the VNC disconnects. I've used a couple Linux desktops with it and they both disconnect after a couple minutes. Any ideas on what I could check for?

**Comment by lopatoid** [comment]
Had similar problem, solved it by running vnc server with following options:
`x11vnc  -noxdamage -ncache_cr -forever -notruecolor -noxfixes  -shared -display :0`
