### ISSUE TITLE
Fresh install 1.1 with FreeRDP

### ISSUE THREAD

**Issue by cmduluth** [MysticRyuujin/guac-install#125]
i just did a fresh install Ubuntu 18.04 with freerdp 2 and over a couple hours time I have a guacd process slowly grab more and more RAM to the point where it crashes. 8GB of RAM and seems to escalate quickly after 5 users are on.

Thoughts?
![Screenshot from 2020-04-03 14-09-52](https://user-images.githubusercontent.com/53790596/78396341-d5d09080-75b4-11ea-833f-0d2a975e52af.png)

**Comment by cmduluth** [comment]
RAM seems to climb when users are on a machine and doing anything graphically intensive.

**Comment by MysticRyuujin** [comment]
You should open an issue who Guacamole
