### ISSUE TITLE
GUACAMOLE_HOME with user defined directory

### ISSUE THREAD

**Issue by nagarjunakalukuri** [MysticRyuujin/guac-install#127]
by default GUACAMOLE_HOME is poineted /etc/guacamole/
here we need to modify the default path according to user config home directory.
please give us the required modifications.

**Comment by nagarjunakalukuri** [comment]
Overriding GUACAMOLE_HOME
If you cannot or do not wish to use /etc/guacamole for GUACAMOLE_HOME, the location can be overridden through any of the following methods:

Creating a directory named .guacamole, within the home directory of the user running the servlet container. This directory will automatically be used for GUACAMOLE_HOME if it exists.

Specifying the full path to an alternative directory with the environment variable GUACAMOLE_HOME. Be sure to consult the documentation for your servlet container to determine how to properly set environment variables.

Specifying the full path to an alternative directory with the system property guacamole.home.

**Comment by nagarjunakalukuri** [comment]
the above mentioned process getting failed .
Can any one have better solutions with using tomcat server ?

**Comment by MysticRyuujin** [comment]
I have no idea what the issue is...

**Comment by nagarjunakalukuri** [comment]
we are failing to change the guacamole_home environment path which is by default pointed to /etc/guacamole.

any idea or procedure to set the GUACAMOLE_HOME="/opt/webBasedConsoles"
under /opt/webBasedConsoles directory will contaion
extentions/*.jars files
guacamole.properties
guacd.confg
lib/mysql or postgres jars

**Comment by MysticRyuujin** [comment]
This is repo is for the script and issues with the script, it is not for general Guacamole support. You'd be better off reaching out on their direct support forms to get an answer. I'll leave the issue open here in case someone else wants to provide some input.

I know you'll need to fix line 449 `ln -sf /etc/guacamole/guacamole.war /var/lib/${TOMCAT}/webapps/`

Then you'll likely need to follow the instructions in the documentation:

> Overriding GUACAMOLE_HOME
> If you cannot or do not wish to use /etc/guacamole for GUACAMOLE_HOME, the location can be overridden through any of the following methods:
> 
> Creating a directory named .guacamole, within the home directory of the user running the servlet container. This directory will automatically be used for GUACAMOLE_HOME if it exists.
> 
> Specifying the full path to an alternative directory with the environment variable GUACAMOLE_HOME. Be sure to consult the documentation for your servlet container to determine how to properly set environment variables.
> 
> Specifying the full path to an alternative directory with the system property guacamole.home.

**Comment by nagarjunakalukuri** [comment]
@MysticRyuujin 
Thank you for suggestion and will follow the mentioned procedure.
