### ISSUE TITLE
Microphone not working via RDP to Win10 desktop. Speakers/audio works OK.

### ISSUE THREAD

**Issue by teal67** [MysticRyuujin/guac-install#129]
Hi. Just did an install via the script on  Ubuntu 18.04. When connecting to a Windows 10; the microphone is not redirected over. i.e. going into Windows Sounds and testing the remote mic shows that no audio is being sent over.
However, performing a direct RDP connection over using the native Windows RDP client works.

When running guacd in foreground and debug mode, the following logs are captured. It looks like audio input is being sent over to guacd, but somehow the remote Windows 10 machine is not picking it up. Could it be an issue with the FreeRDP build?  Am using FreeRDP as recommended in the main page.

guacd[13302]: INFO:     Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[13302]: DEBUG:    Unable to bind socket to host ::1, port 4822: Address family not supported by protocol
guacd[13302]: DEBUG:    Successfully bound socket to host 127.0.0.1, port 4822
guacd[13302]: INFO:     Listening on host 127.0.0.1, port 4822
guacd[13302]: INFO:     Creating new client for protocol "rdp"
guacd[13302]: INFO:     Connection ID is "$fb38633b-793f-475f-b650-49e3739249c1"
guacd[13306]: DEBUG:    Processing instruction: size
guacd[13306]: DEBUG:    Processing instruction: audio
guacd[13306]: DEBUG:    Processing instruction: video
guacd[13306]: DEBUG:    Processing instruction: image
guacd[13306]: DEBUG:    Processing instruction: timezone
guacd[13306]: DEBUG:    Parameter "console" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "console-audio" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "disable-auth" omitted. Using default value of 0.
guacd[13306]: INFO:     No security mode specified. Defaulting to security mode negotiation with server.
guacd[13306]: DEBUG:    User resolution is 1454x999 at 96 DPI
guacd[13306]: DEBUG:    Parameter "dpi" omitted. Using default value of 96.
guacd[13306]: DEBUG:    Using resolution of 1452x999 at 96 DPI
guacd[13306]: DEBUG:    Parameter "read-only" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "client-name" omitted. Using default value of "Guacamole RDP".
guacd[13306]: DEBUG:    Parameter "enable-wallpaper" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "enable-theming" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "enable-font-smoothing" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "enable-full-window-drag" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "enable-desktop-composition" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "enable-menu-animations" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "disable-bitmap-caching" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "disable-offscreen-caching" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "disable-glyph-caching" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "color-depth" omitted. Using default value of 16.
guacd[13306]: DEBUG:    Parameter "disable-audio" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "enable-printing" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "printer-name" omitted. Using default value of "Guacamole Printer".
guacd[13306]: DEBUG:    Parameter "enable-drive" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "drive-name" omitted. Using default value of "Guacamole Filesystem".
guacd[13306]: DEBUG:    Parameter "drive-path" omitted. Using default value of "".
guacd[13306]: DEBUG:    Parameter "create-drive-path" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "timezone" omitted. Using default value of "Asia/Bangkok".
guacd[13306]: DEBUG:    Parameter "enable-sftp" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "sftp-hostname" omitted. Using default value of "10.20.34.87".
guacd[13306]: DEBUG:    Parameter "sftp-port" omitted. Using default value of "22".
guacd[13306]: DEBUG:    Parameter "sftp-username" omitted. Using default value of "".
guacd[13306]: DEBUG:    Parameter "sftp-password" omitted. Using default value of "".
guacd[13306]: DEBUG:    Parameter "sftp-passphrase" omitted. Using default value of "".
guacd[13306]: DEBUG:    Parameter "sftp-root-directory" omitted. Using default value of "/".
guacd[13306]: DEBUG:    Parameter "sftp-server-alive-interval" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "recording-name" omitted. Using default value of "recording".
guacd[13306]: DEBUG:    Parameter "recording-exclude-output" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "recording-exclude-mouse" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "recording-include-keys" omitted. Using default value of 0.
guacd[13306]: DEBUG:    Parameter "create-recording-path" omitted. Using default value of 0.
guacd[13306]: INFO:     Resize method: none
guacd[13306]: DEBUG:    Parameter "gateway-port" omitted. Using default value of 443.
guacd[13306]: INFO:     User "@dbf15fc7-c207-4f62-9b1a-48c8a9c29462" joined connection "$fb38633b-793f-475f-b650-49e3739249c1" (1 users now present)
guacd[13306]: DEBUG:    Client is using protocol version "VERSION_1_1_0"
guacd[13306]: INFO:     Loading keymap "base"
guacd[13306]: INFO:     Loading keymap "en-us-qwerty"
guacd[13306]: DEBUG:    freerdp_connect:freerdp_set_last_error_ex resetting error state
guacd[13306]: DEBUG:    Support for CLIPRDR (clipboard redirection) registered. Awaiting channel connection.
guacd[13306]: DEBUG:    Support for static channel "rdpdr" loaded.
guacd[13306]: DEBUG:    Support for static channel "rdpsnd" loaded.
guacd[13306]: DEBUG:    Local framebuffer format  PIXEL_FORMAT_BGRX32
guacd[13306]: DEBUG:    Remote framebuffer format PIXEL_FORMAT_RGB16
guacd[13306]: DEBUG:    primitives autodetect, using optimized
guacd[13306]: DEBUG:    freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
guacd[13306]: DEBUG:    freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
guacd[13306]: DEBUG:    CLIPRDR (clipboard redirection) channel connected.
guacd[13306]: DEBUG:    SVC "rdpdr" connected.
guacd[13306]: DEBUG:    SVC "rdpsnd" connected.
guacd[13306]: DEBUG:    Loading Dynamic Virtual Channel guacai
guacd[13306]: DEBUG:    AUDIO_INPUT plugin loaded.
guacd[13306]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[13306]: DEBUG:    [cliprdr_packet_format_list_new] called with invalid type 00000000
guacd[13306]: DEBUG:    User is requesting to provide audio input as 2-channel, 44100 Hz PCM audio at 2 bytes/sample.
guacd[13306]: INFO:     Connected to RDPDR 1.13 as client 0x0004
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0001, length=44
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0002, length=8
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0003, length=8
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0004, length=8
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0005, length=8
guacd[13306]: DEBUG:    Sending capabilities...
guacd[13306]: DEBUG:    Capabilities sent.
guacd[13306]: DEBUG:    Client ID confirmed
guacd[13306]: DEBUG:    rdp_set_error_info:freerdp_set_last_error_ex resetting error state
guacd[13306]: DEBUG:    [cliprdr_packet_format_list_new] called with invalid type 00000000
guacd[13306]: INFO:     Connected to RDPDR 1.13 as client 0x0003
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0001, length=44
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0002, length=8
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0003, length=8
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0004, length=8
guacd[13306]: DEBUG:    Ignoring server capability set type=0x0005, length=8
guacd[13306]: DEBUG:    Sending capabilities...
guacd[13306]: DEBUG:    Capabilities sent.
guacd[13306]: DEBUG:    Client ID confirmed
guacd[13306]: INFO:     RDPDR user logged on
guacd[13306]: DEBUG:    All supported devices sent.
guacd[13306]: DEBUG:    New AUDIO_INPUT channel connection
guacd[13306]: DEBUG:    RDP server is accepting audio input as 2-channel, 44100 Hz PCM audio at 2 bytes/sample.
guacd[13306]: INFO:     Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[13306]: DEBUG:    AUDIO_INPUT channel connection closed
guacd[13306]: DEBUG:    New AUDIO_INPUT channel connection
guacd[13306]: DEBUG:    RDP server is accepting audio input as 2-channel, 44100 Hz PCM audio at 2 bytes/sample.
guacd[13306]: DEBUG:    User is requesting to provide audio input as 2-channel, 44100 Hz PCM audio at 2 bytes/sample.

**Comment by MysticRyuujin** [comment]
Debugging audio issues is outside the scope of this script, I wouldn't even know where to start and since nobody else has chimed in, I'm going to close. I suggest reaching out on official guac forms.
