### ISSUE TITLE
TOTP wont work

### ISSUE THREAD

**Issue by antoweb** [MysticRyuujin/guac-install#131]
After first install on debian buster 10 and after scanned the qr code the token inserted is invalid so unable to login. How to correct this problem or disable temporary otp?

**Comment by MysticRyuujin** [comment]
You'll need to modify the database.

https://issues.apache.org/jira/browse/GUACAMOLE-770

```
UPDATE `guacamole_user_attribute` SET `attribute_value` = 'false' WHERE `guacamole_user_attribute`.`user_id` = 3 AND `guacamole_user_attribute`.`attribute_name` = 'guac-totp-key-confirmed';
```

**Comment by antoweb** [comment]
Thanks MysticRyuujin but doesnt work.
