### ISSUE TITLE
Firewall is blocking sometimes

### ISSUE THREAD

**Issue by FelipeEsBr** [MysticRyuujin/guac-install#132]
ufw allow 8080 comment 'tomcat allowed'

**Comment by MysticRyuujin** [comment]
So I'm not very familiar with ufw and how it works/behaves, it's off by default on most Ubunutu/Debian installs I've ran. I checked my Ubuntu 18.04 and when I run `sudo ufw status` I get `Status: inactive`

Would something like this fix it?

```
if [[ $(ufw status | grep inactive | wc -l) -eq 0 ]]; then
    ufw allow 8080 comment 'tomcat allowed'
fi
```

I don't know enough about ufw to know if that's a "universal fix" that I should include here.
