### ISSUE TITLE
mysql-utilities issue during Ubuntu 20.04 install

### ISSUE THREAD

**Issue by mspalan** [MysticRyuujin/guac-install#134]
Hello,
I tried to run guac-install script under Ubuntu 20.04 but I receive this error from log file:
E: Impossible de trouver le paquet mysql-utilities
(Impossible to find package).

Can you please help me?
Best regards,
Marc.

**Comment by MysticRyuujin** [comment]
20.04 just came out, the error is pretty clear, there's no package called `mysql-utilities` in the default apt repos. I'm not entirely sure why. The script does add the universe repo.

You'll either need to run 18.04 or wait for an updated script or for someone to post a workaround until then...

If I get some time I'll look into it. I was planning on being lazy until the next Guac release

**Comment by MysticRyuujin** [comment]
https://launchpad.net/ubuntu/focal/+source/mysql-utilities

>There is no current release of this source package in The Focal Fossa. You can still report bugs, make translations, and so on, but they might not be used until the package is published.

**Comment by MysticRyuujin** [comment]
I'm not 100% certain that you actually need `mysql-utilities` in order for the script to complete and install...

You can try removing `mysql-utilities` from the apt install command and see if it still works. It's worth a shot. I don't remember exactly why it was installed originally

**Comment by mspalan** [comment]
I've removed mysql-utilities package and the installation is OK now. I was not sure if it was OK to proceed like that, it works ! Thanks for your support.
