### ISSUE TITLE
Configure RDP connection to windows 10

### ISSUE THREAD

**Issue by pengyang-sh** [MysticRyuujin/guac-install#137]
![image](https://user-images.githubusercontent.com/62085193/82288511-371db900-99d5-11ea-9635-7496971950a9.png)

**Comment by pengyang-sh** [comment]
I setup Apache guacamole-1.0.0 on Linux CentOS VM. I configure the user in the user-mapping.xml, when I login , I see the notice.
![image](https://user-images.githubusercontent.com/62085193/82288727-b612f180-99d5-11ea-87a9-010cfa467dbe.png)
What lead to the problem? Can you help me?

**Comment by MysticRyuujin** [comment]
https://github.com/MysticRyuujin/guac-install/issues/89#issuecomment-553107254
