### ISSUE TITLE
Unable to run script using MySQL DB hosted on another Linux server

### ISSUE THREAD

**Issue by jwagner77** [MysticRyuujin/guac-install#140]
I have MySQL installed on a seperate Ubuntu 18.04 server. Guac-Properties points to the remote server, but the script only prompts for the MySQL Root Password and then tries to login to a MySQL instance on the local host. I have tried different tags but none have let me bypass this issue and connect to the remote database for updating.

**Comment by MysticRyuujin** [comment]
Are you referring to the upgrade script or the install script?

**Comment by MysticRyuujin** [comment]
I'm going to assume you're talking about the upgrade script since you've already got a guac-properties file...

Run this:
`grep -oP 'mysql-hostname:\K.*' /etc/guacamole/guacamole.properties | awk '{print $1}'`

That does it give back?

**Comment by jwagner77** [comment]
Yes, sorry, I am trying to use the upgrade script. Running the command you gave me prints out the IP of the remote database server.

**Comment by MysticRyuujin** [comment]
Do you know at what point the script fails??

Here are all of the times it calls mysql:

```
mysql -u root -D ${guacDb} -h ${mysqlHost} -P ${mysqlPort} -e"quit" || exit 1

mysql -u root -D ${guacDb} -h ${mysqlHost} -P ${mysqlPort} -e"quit" && break

mysql -u root -D ${guacDb} -h ${mysqlHost} -P ${mysqlPort} < guacamole-auth-jdbc-${GUACVERSION}/mysql/schema/upgrade/${FILE}
```

Unless your password is wrong, or something it's working with the `-h` there, I'm not sure what or why it would try to login to the local instance...

**Comment by jwagner77** [comment]
I am not completely sure, but it looks like the script is defaulting to use root for mysql as it prompts for the MySQL Root Password when I run the script. I commented out the part of the script where it would prompt for the Root password and it looks like it ran successfully. I am reviewing the system still to confirm but there are now 1.1.0 plugins installed so at least part of it ran.

**Comment by MysticRyuujin** [comment]
Yes, the script asks for and expects the root account/password.

If you don't want to use the root, but instead another authorized account, you'll have to edit accordingly.

I will see about adding the functionality to not use root when I feel like tinkering...
