### ISSUE TITLE
guac-install.sh please check script line 659

### ISSUE THREAD

**Issue by comsyspro** [MysticRyuujin/guac-install#141]
line 659
`    
if [[ $(iptables --list-rules | grep -- "-p tcp" | grep -- "--dport 22" | grep -- "-j ACCEPT" | wc -l) -eq 0 ]]; then`

This iptable check should probably be on port 8080 like:
line 659
`    
if [[ $(iptables --list-rules | grep -- "-p tcp" | grep -- "--dport 8080" | grep -- "-j ACCEPT" | wc -l) -eq 0 ]]; then`

Also it would be practical to also add here a check for: 
ufw allow "Apache Secure" 
or 
ufw allow "Apache Full"

**Comment by MysticRyuujin** [comment]
Fixed the 22/8080 line

I'm not planning on supporting 443 with this script because I typically put guac behind NGINX anyway...and there's 100 ways to do it...

I would probably approve a pull request that did more but I don't really have plans to do it myself or support it right now.
