### ISSUE TITLE
Cannot update Debian package due to mismatched directory

### ISSUE THREAD

**Issue by rasmysamy** [MysticRyuujin/guac-install#142]
Hello,

The script currently fails to completely update Guacamole when it is installed using the Debian package. This is because the update script expects the webapp to be placed in /etc/guacamole, while the Debian package places Guacamole in /var/lib/tomcat8. 

Would it be possible for the update script to detect if there is already a guacamole install in /var/lib/tomcat[8] and update it there (or maybe even symlink /etc/guacamole and continue as normal)?

Thanks a lot!

**Comment by MysticRyuujin** [comment]
How did you install?
