### ISSUE TITLE
1.2.0

### ISSUE THREAD

**Issue by pablopol24** [MysticRyuujin/guac-install#143]
hello, script update to 1.2.0?

**Comment by MysticRyuujin** [comment]
I didn't even know it was released until you opened this issue 😉 

Depends on how much has changed and how hard it will be to switch to the new DB format.

You're welcome to try changing the version number to 1.2.0 and reporting back haha

I've got a lot going on right now, so it might be a little while.

**Comment by pablopol24** [comment]
you were correct, it works !!!
