### ISSUE TITLE
Need to add support for guacamole 1.2.0 new branch installations suppport from the scripts.

### ISSUE THREAD

**Issue by nagarjunakalukuri** [MysticRyuujin/guac-install#144]
https://guacamole.apache.org/releases/1.2.0/
please check this new version for support for 1.2.0

**Comment by UpperM** [comment]
I just went to 1.2.0 without problem, just edited the version in the script

**Comment by MysticRyuujin** [comment]
I'm aware, another user just changed the version # in the script and reported that it worked. Try it and report back.

I'm working on moving mariadb too, takes time.

**Comment by UpperM** [comment]
> 
> 
> I'm aware, another user just changed the version # in the script and reported that it worked. Try it and report back.
> 
> I'm working on moving mariadb too, takes time.

Yup that was me but I deleted my comment because I can't connect to rdp.

I've setup a fresh server with guac-install.sh and have the same issue.

I don't if it's from my setup or from the script.

**Comment by UpperM** [comment]
My god, just wrong password ... Still have an issue on rdp connection but I think it's on my side
``Connection to guacd terminated abnormally: Connection to guacd timed out``

**Comment by SoulSeekkor** [comment]
@MysticRyuujin  Just opened a pull request with changes for 1.2.0 as well as a missing package.
