### ISSUE TITLE
Guacamole - Debian 10  - update 1.1 to 1.2   -- Crash login to guacamole

### ISSUE THREAD

**Issue by marttux** [MysticRyuujin/guac-install#146]
Hello. After the update, no account can be logged in on the reservation welcome page.
The accounts are in mysql. Each attempt ends with an "invalid login"
Is there a solution?
thank you for the info

**Comment by nayra42** [comment]
@marttux I have a similar  issue going from 1.0 to 1.2 on Ubuntu 16.04.  Did you notice on your screen on the bottom right of the login screen what version it says?  I think something is not making the switch over from the old site to the new site.  I am still troubleshooting but that is as far as I have gotten.

**Comment by nayra42** [comment]
Hey @marttux I re-downloaded the .war file for 1.2 and replaced the old .war file with it and i am in business.  https://guacamole.apache.org/releases/1.2.0/  Try DL the .war from here, mv your old .war to a location as a backup and move the new one in with the same name as the old one.

**Comment by marttux** [comment]
Hi,


I was all worried that I was still worried for a while and the mistake was brown in two things. (Both about me)
1) guacamole path / var / lib / tomcatX / webaps / guacamole <- I have more installations here (error in the future if symlink fails).

Ver.Guacamole in the lower right corner 1.2

2) The mysql bug is fixed after re-importing the DB.

A) export of functional DB:
mysql -p -u root guacamole_db </schema/guacamole_db.sql
B) login to the mysql DB
  mysql -u root -p
C) deleting DB Guacamole
DROP DATABASE guacamole_db;
D) creation of a new DB
create database guacamole_db;
E) go to the rsp database to use guacamole_db
use guacamole_db;
F) import of schemes
source /schema/001-create-schema.sql;
source /scheme/002-create-admin-user.sql;
G) inserting a backup of the original DB
source /schema/guacamole_db.sql;
