### ISSUE TITLE
Guacamole only works on localhost (server)

### ISSUE THREAD

**Issue by toprawa** [MysticRyuujin/guac-install#147]
I installed guacamole 1.2.0 on ubuntu 20.04 LTS using the installation script. Everything works correctly on localhost but not on a remote computer. If I open guacamole on the server where I installed it I can connect to any computer but if I open guacamole in the browser of another computer it does not connect to any computer.I use authbind on port 80. 

- Mysql and Tomcat version default.
- No MFA

Thank you and a greeting. Good job.

**Comment by MysticRyuujin** [comment]
Sounds like your issue has nothing to do with the script and more to do with your environment / modifications to use port 80...

All I can suggest is that if you can use port 80 from the localhost that you installed it on just fine to check your firewall rules and ensure that you can hit that server's port 80 remotely.

Also, depending on how you bound port 80, you might only be accepting connections from localhost/127.0.0.1 - you might need to bind to 0.0.0.0 or [:::80], etc.

**Comment by toprawa** [comment]
The script works perfectly. I understand that port 80 works properly because I can open guacamole and log in from any computer. Thanks again.
