### ISSUE TITLE
connecting to windows server 2012r2

### ISSUE THREAD

**Issue by killmasta93** [MysticRyuujin/guac-install#148]
Hi
I was currently trying to configure on a windows server 2012r2 config but on the log i get this

```
Jul 19 14:38:37 smarthome guacd[11219]: Loading keymap "base"
Jul 19 14:38:37 smarthome guacd[11219]: Loading keymap "en-us-qwerty"
Jul 19 14:38:38 smarthome guacd[11219]: Error connecting to RDP server
Jul 19 14:38:38 smarthome guacd[11219]: User "@5e43d8d6-a74b-4dce-98b0-b6b38fa2293c" disconnected (0 users remain)
Jul 19 14:38:38 smarthome guacd[11219]: Last user of connection "$08a7c586-56f0-48fd-b027-572ed9f68d8a" disconnected
Jul 19 14:38:38 smarthome tomcat9[10542]: 14:38:38.260 [http-nio-8080-exec-9] INFO  o.a.g.tunnel.TunnelRequestService - User "guacadmin" disconnected from connection "1". Duration: 523 milliseconds
Jul 19 14:38:38 smarthome tomcat9[10542]: Exception in thread "Thread-32" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:425)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
Jul 19 14:38:38 smarthome tomcat9[10542]: #011at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
Jul 19 14:38:38 smarthome guacd[10879]: Connection "$08a7c586-56f0-48fd-b027-572ed9f68d8a" removed.

```

This is my config

![image](https://user-images.githubusercontent.com/13953629/87883542-bfb4d780-c9cd-11ea-876d-cdc61143d372.png)

![image](https://user-images.githubusercontent.com/13953629/87883585-16221600-c9ce-11ea-83b3-327c3bcf9773.png)

the rest is default

Thank you

**Comment by MysticRyuujin** [comment]
Are you using a Remote Desktop Gateway? Or did you mean to put the IP under the Network section?
![image](https://user-images.githubusercontent.com/8877131/87883681-95afe500-c9ce-11ea-95fc-888be34b29af.png)

**Comment by killmasta93** [comment]
yeah my bad i had to put in the network section its working now

**Comment by killmasta93** [comment]
just quick question, on the RDP printing directed i see it creates the PDF which on the local host it gets downloaded automatically, but is it possible to automatically print on the printer of the host? or ask for the option which printer to choose to print on the local host?

**Comment by MysticRyuujin** [comment]
I have no idea 😄 I actually don't use guacamole very often myself and I've never used it for printing. Might be more appropriate to ask on one of the other forums.

**Comment by killmasta93** [comment]
thanks ill keep searching what i did find is something on the wiki
`While it is technically possible to cause the PDF to automatically open a print dialog, and on some browsers it is also possible to automatically open the PDF, this does not currently work reliably across all platforms,`
