### ISSUE TITLE
tomcat packages dont exist

### ISSUE THREAD

**Issue by peebowo** [MysticRyuujin/guac-install#151]
Read MySQL root's password from command line argument

Read MySQL guacamole_user's password from command line argument

Updating apt...
All packages are up to date.
lib{mariadb,mysql}-java not available. Will download mysql-connector-java-8.0.19.tar.gz and install manually
**Failed. Can't find Tomcat package**

**Comment by MysticRyuujin** [comment]
What OS?

**Comment by peebowo** [comment]
Idk but im using kali

**Comment by MysticRyuujin** [comment]
I'm afraid the script only supports Ubuntu and Debian at this time.

It's certainly possible to add Kali support but it would require figuring out all of the missing packages and then coding them into the distribution specific section of the scrip...such as tomcat apparently.

At the point the script crashed, it was looking for the tomcat package...

**Comment by peebowo** [comment]
I saw this on kali.org but ok thx!

**Comment by MysticRyuujin** [comment]
Wow, I didn't know about that. That's cool. I'm guessing that the author of that left off some key configuration like adding a repository that you didn't install? If you can Google why tomcat9 doesn't appear in your apt cache it might work...

**Comment by MysticRyuujin** [comment]
If you run this command, it should return the tomcat package, if it doesn't...then it might be something we can fix in the script.

`apt-cache show tomcat9`

**Comment by MysticRyuujin** [comment]
I 100% take it back, Kali Linux should be supported, I just forgot

**Comment by MysticRyuujin** [comment]
Also, check the documentation here: https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
