### ISSUE TITLE
Automatically check if upgrade is possible and upgrade when necessary

### ISSUE THREAD

**Issue by miszterx** [MysticRyuujin/guac-install#152]
Thanks for the scripts. It is huge help for me. I used it for install the guacamole and even upgrade it.

As far as I can see currently this is a manual task. In case you realize there is a newer version, download the script and and run the guac-upgrade.sh with the flags or even interactive. 

Will it be possible to download the fresh script, run it with predefined flags (or even read it from config) and the script can detect the current version and just trigger the upgrade in case of new version?

In this case send an email about upgrade was triggered and check the service. In my "home" environment this kind of possibility would be useful.

Thanks.

**Comment by MysticRyuujin** [comment]
Guacamole doesn't really update frequently enough for that to be all that useful. The amount of work vs the reward there doesn't seem worth it. From 1.0.0 to 1.1.0 it was a year, and 1.2.0 was 6 months.

This would be functionality that I would suggest that you scripted for yourself if you were so inclined to do so. It wouldn't be significantly difficult, you could use a `git fetch` script to watch for changes to the upgrade script, check if the version number changed, and run it.

But again, is that worth the effort? Probably not...and I can't imagine there being a ton of people that want their system to automatically download and run a script (as root none the less) based off some random dude's GitHub 😉
