### ISSUE TITLE
An error has occurred and this action cannot be completed. If the problem persists, please notify your system administrator or check your system logs.

### ISSUE THREAD

**Issue by johnczer** [MysticRyuujin/guac-install#153]
Thank you for creating this script!  Everything seems to install and no errors after your script runs but when trying to access Apache Guacamole at http://IP Address:8080/guacamole/  I get the following:
An error has occurred and this action cannot be completed. If the problem persists, please notify your system administrator or check your system logs. Any help would be appreciated.

**Comment by MysticRyuujin** [comment]
Have you tried to reboot after installation?

If yes, I would double check that the correct symlinks were created between the files in /etc/guacamole and the /var/tomcat folder

**Comment by johnczer** [comment]
Thanks.  I did try the restart first but no luck. So what I have for symlinks are /var/lib/tomcat9/conf pointing to /etc/tomcat9, /var/lib/tomcat9/logs pointing to /var/log/tomcat9/ and /var/lib/tomcat9/work pointing to /etc/tomcat9/Catalina. Could you elaborate on the MySQL connector?

**Comment by MysticRyuujin** [comment]
`cat guac-install.sh | grep "ln -s"`

Check that the appropriate links exist.

**Comment by johnczer** [comment]
I get this result from running that: cat: guac-install.sh: cat: guac-install.sh: No such file or directory

**Comment by johnczer** [comment]
Sorry, I was running in wrong location.  Here is the output:
ln -sf /etc/guacamole/guacamole.war /var/lib/${TOMCAT}/webapps/
    ln -sf /usr/share/java/mariadb-java-client.jar /etc/guacamole/lib/mariadb-java-client.jar
    ln -sf /usr/share/java/mysql-connector-java.jar /etc/guacamole/lib/mysql-connector-java.jar

**Comment by MysticRyuujin** [comment]
I'm not going to be able to walk you through this line by line, sorry dude.

I'd suggest starting from scratch, it's probably faster and easier than walking you through each and every thing to check.

Maybe an alternative is to post your log file here, maybe there's a clue in there.

**Comment by johnczer** [comment]
I understand.  I have tried running your script several times and get the same result. I will post my logs but which ones would be helpful so I don't upload rubbish?

**Comment by johnczer** [comment]
[guacamole.zip](https://github.com/MysticRyuujin/guac-install/files/5114807/guacamole.zip)

**Comment by MysticRyuujin** [comment]
The installation log is here:
# Log Location
LOG="/tmp/guacamole_${GUACVERSION}_build.log"

**Comment by johnczer** [comment]
I do see that in your script but there is no log in that folder with that name. Were the ones I uploaded of any help?

**Comment by MysticRyuujin** [comment]
Is there one with the name:
`/tmp/guacamole_0.2.0_build.log` ?

**Comment by johnczer** [comment]
No, nothing with that name-weird!

**Comment by johnczer** [comment]
The strange thing is I can check the status of tomcat9 and guacd and mysql and all seems normal, at least things appear to be running.

**Comment by MysticRyuujin** [comment]
There is an error in the logs you sent me:
```
23-Aug-2020 14:50:15.390 WARNING [Thread-3] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [guacamole] appears to have started a thread named [com.google.inject.internal.util.$Finalizer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.8/java.lang.Object.wait(Native Method)
 java.base@11.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
 java.base@11.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
 com.google.inject.internal.util.$Finalizer.run(Finalizer.java:114)
```

Did you try to install with TOTP? Maybe try without?

**Comment by MysticRyuujin** [comment]
I find it almost impossible to believe that there isn't an log under that /tmp/ folder unless it was deleted...

Perhaps try running it again, one more time, but checking for the log file as soon as it completes?

**Comment by johnczer** [comment]
Yeah, so the first few times I did try install with TOTP but then after no success I tried multiple times without and still here we are. I am so sorry for the hassle.

**Comment by johnczer** [comment]
Ok, I will try this.  Would the upgrade script also generate this log?  Or should I try a complete reinstall?

**Comment by MysticRyuujin** [comment]
Complete re-install. I also found a thread that I myself opened 4 years ago about that error lmao, the guacamole developers said it's safe to ignore.

**Comment by johnczer** [comment]
So initially the same result.  One thing I can do to get this to work is to change the guacamole.properties to:
# Hostname and port of guacamole proxy
guacd-hostname: localhost
guacd-port:     4822

# Authentication provider class
auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider

# Properties used by BasicFileAuthenticationProvider
basic-user-mapping: /etc/guacamole/user-mapping.xml

Which is what the Apache site says should be the minimum parameters.  What was in there originally after I installed using the script was:
mysql-hostname: localhost
mysql-port: 3306
mysql-database: guacamole_db
mysql-username: guacamole_user
mysql-password: guacuserpassword (Masked for security)

So one thing I am not sure of is missing or is normal is when I log into http://IP-Address:8080/guacamole/#/
and I click on settings I cannot see the normal tabs to manage connections, users, etc.  Am I missing something?

**Comment by johnczer** [comment]
This is the section I am referring to that I am not able to see when logging in:

https://guacamole.apache.org/doc/gug/administration.html

**Comment by johnczer** [comment]
I just wanted to give you an update on this... I was finally able to get this to work by simply fixing the timezone error in mysql.  I noticed that everything seemed to start and run until I tried to load the http://localhost:8080/guacamole page and then I would get the error message described above and noticed tomcat would crash-everytime!  What a headache for such a simple (but handy app).  Oh well...in the end-I won!  Thank for your help.

**Comment by cfrv99** [comment]
@johnczer Hi how to solved this timezone fixing? Could you please share it with me ?

**Comment by cfrv99** [comment]
@johnczer Hi, How did you solve this timezone problem? Could you please share it with me ?

**Comment by cfrv99** [comment]
@MysticRyuujin I have the same error, but I cannot to solve it.

**Comment by R4wd0g** [comment]
> @MysticRyuujin I have the same error, but I cannot to solve it.

Did you manage to solve it?

**Comment by ppbronisz** [comment]
I met the same issue when working with version 1.5. When I added guacamole-1.4.0.war, no error. I checked also tomcat logs, the following message appear when I try to connect:
16:27:50.890 [http-nio-8080-exec-6] WARN  o.a.g.e.AuthenticationProviderFacade - The "mysql" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set "skip-if-unavailable: mysql" within your guacamole.properties.
16:27:50.900 [http-nio-8080-exec-6] ERROR o.a.g.rest.RESTExceptionMapper - Unexpected internal error:
### Error querying database.  Cause: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/guacamole_db
### The error may exist in org/apache/guacamole/auth/jdbc/user/UserMapper.xml
### The error may involve org.apache.guacamole.auth.jdbc.user.UserMapper.selectOne
### The error occurred while executing a query
### Cause: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/guacamole_db
