### ISSUE TITLE
Can you add an installation with Active Directory Integration?

### ISSUE THREAD

**Issue by ghost** [MysticRyuujin/guac-install#156]
It, could be fantastic if you can add an installation with Active Directory authentication for the web access.

**Comment by MysticRyuujin** [comment]
There isn't an "active directory" module, per-say.

There is an LDAP module, a SAML module, and a RADIUS module...but installing and configuring those is a bit out of scope for this script...

You can use this script as a starting point, swapping out the optional modules for TOTP with the module of your choice...but against, configuration of one of those modules is more involved and requires setup outside of what the script can do.
