### ISSUE TITLE
All Type of connections not work

### ISSUE THREAD

**Issue by Ne085** [MysticRyuujin/guac-install#158]
Here are some images that demonstrate the correct install as per guide:
![Schermata da 2020-10-20 12-32-59](https://user-images.githubusercontent.com/53598198/96575285-dd495400-12d0-11eb-92e0-7f55fd3d74ce.png)
![Schermata da 2020-10-20 12-33-06](https://user-images.githubusercontent.com/53598198/96575299-e0dcdb00-12d0-11eb-9ae1-efacffdab120.png)
![Schermata da 2020-10-20 12-33-20](https://user-images.githubusercontent.com/53598198/96575308-e33f3500-12d0-11eb-9cd4-dc8a36dbcb5d.png)
![Schermata da 2020-10-20 12-33-35](https://user-images.githubusercontent.com/53598198/96575317-e508f880-12d0-11eb-84c3-7ee4ed12b0bd.png)
![Schermata da 2020-10-20 12-33-42](https://user-images.githubusercontent.com/53598198/96575328-e6d2bc00-12d0-11eb-9165-aff523bde3ab.png)

Below is the error image that comes out with any type of connection:
![Schermata da 2020-10-20 12-37-00](https://user-images.githubusercontent.com/53598198/96575469-0ff34c80-12d1-11eb-9923-4964645335ea.png)

I can also show that with version 1.0.0, always installed with Chase's scrypt, everything works correctly.
Same machines, same everything ... only the guacamole version changes

N.B. -->
![Schermata da 2020-10-20 12-40-41](https://user-images.githubusercontent.com/53598198/96575990-c48d6e00-12d1-11eb-9d09-a025649ed3f2.png)
![Schermata da 2020-10-20 12-40-59](https://user-images.githubusercontent.com/53598198/96575993-c6efc800-12d1-11eb-8ecf-bf79467d93ce.png)
![Schermata da 2020-10-20 12-41-56](https://user-images.githubusercontent.com/53598198/96576004-c9eab880-12d1-11eb-9fe6-e9988d78a70f.png)

Please, I need help urgently

**Comment by gripfastistech** [comment]
I initially had this same message upon login trying to use RDP, then after copying your image's input fields you used as examples (but with my details) I was able to login without issue. My script install date was 01-28-2021 so I can attest the script install works.
