### ISSUE TITLE
Remote mysql

### ISSUE THREAD

**Issue by pablopol24** [MysticRyuujin/guac-install#163]
Hello !
My mysql base is remote the script tries to connect as root when I want to update, that is not possible.
Can you modify?

**Comment by MysticRyuujin** [comment]
Hmmm it would take some time to add a new variable and test all of the scenarios of install/don't install/local/remote

I'll think about doing this at some point, but you're probably much better off just doing a find/replace in the script for "mysql" and just add your username to the lines.

**Comment by pablopol24** [comment]
I could update by modifying the lines
Thank you !!
