### ISSUE TITLE
configure fails due to dev version of FreeRDP

### ISSUE THREAD

**Issue by jamesallerton** [MysticRyuujin/guac-install#164]
I'm trying to upgrade an existing guacamole 1.2.0 install using the guac-upgrade script on debian 10 but when the script gets to the configure command it runs until an error is hit. The message is as follows:

   --------------------------------------------
   You are building against a development version of FreeRDP. Non-release
   versions of FreeRDP may have differences in behavior that are impossible to
   check for at build time. This may result in memory leaks or other strange
   behavior.

   *** PLEASE USE A RELEASED VERSION OF FREERDP IF POSSIBLE ***

   If you are ABSOLUTELY CERTAIN that building against this version of FreeRDP
   is OK, rerun configure with the --enable-allow-freerdp-snapshots
  --------------------------------------------

The script continues but the make commands subsequently fail due to no makefile:

 make: *** No targets specified and no makefile found.  Stop.

the script then continues to completion.

This appears to be a result of an upstream change to configure to warn people using dev builds of FreeRDP, applying the --enable-allow-freerdp-snapshots to the configure command on line 127 in the update script will allow the build to proceed and the upgrade to complete sucessfully.
I suspect this same issue would occur with new installs using the install version of the script too.

I think this will mainly be a problem for debian installs because of the current released version of FreeRDP. I think adding the --enable-allow-freerdp-snapshots argument only effectively returns things to previous behaviour, but this is where I reach my limit on understanding the implications of such a thing, and there are many people better placed to make that determination.

Hope this helps and thanks for the script.

**Comment by MysticRyuujin** [comment]
We should probably either put a note in the README about this, or make the script break out if that fails. Thanks for reporting though

**Comment by postheimer** [comment]
same problem on debian 10 

all th script is ok , mysql is ok , vnc ,ssh ,... is ok but no connection to rdp

the freerdp stay in version 2.0

**Comment by marius137** [comment]
the issue also exists in the install script. maybe its best to add a command line switch or something like that that allows the use of dev versions of freedrp. a hacky way is to just edit line 413 from `./configure --with-init-dir=/etc/init.d &>> ${LOG}` to ./configure --with-init-dir=/etc/init.d --enable-allow-freerdp-snapshots &>> ${LOG}

**Comment by marius137** [comment]
> 
> 
> same problem on debian 10
> 
> all th script is ok , mysql is ok , vnc ,ssh ,... is ok but no connection to rdp
> 
> the freerdp stay in version 2.0

Disabling audio and glyph caching and manually setting the authentication mode to NLA allowed me to connect to my windows 10 box via RDP. did you check the logs with `sudo journalctl -u guacd.service -f` ?

**Comment by MysticRyuujin** [comment]
> the issue also exists in the install script. maybe its best to add a command line switch or something like that that allows the use of dev versions of freedrp. a hacky way is to just edit line 413 from `./configure --with-init-dir=/etc/init.d &>> ${LOG}` to ./configure --with-init-dir=/etc/init.d --enable-allow-freerdp-snapshots &>> ${LOG}

Did the previous commit not fix that?

**Comment by MysticRyuujin** [comment]
Oh, I see, I patched the upgrade script but not the install script, duh. I'll try to fix that later today, unless one of you wants to submit a pull request 🙂

**Comment by MysticRyuujin** [comment]
Thanks @marius137
