### ISSUE TITLE
Upgrade went smoothly

### ISSUE THREAD

**Issue by stanthewizzard** [MysticRyuujin/guac-install#165]
But now I'm unable to connect to anny computer when using 1.3.0
With guacamol 1.2.0 (and the same db) no issue. I'm connecting

Thanks for help

**Comment by 0xBrAinsTorM** [comment]
Hi,

had the same problem. As soon as it got connected it immediately got disconnected again. The Mailing list suggests it's the option "deactivate Glyph-Caching" -> http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Not-anymore-able-to-login-into-WIndows7-via-RDP-td9899.html

But for me this was not the culprit. Instead it was the option "deactivate audio" which finally solved the problem.

**Comment by stanthewizzard** [comment]
You are totally right
I does work without the sound
Huge thank you

**Comment by stanthewizzard** [comment]
> Hi,
> 
> had the same problem. As soon as it got connected it immediately got disconnected again. The Mailing list suggests it's the option "deactivate Glyph-Caching" -> http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Not-anymore-able-to-login-into-WIndows7-via-RDP-td9899.html
> 
> But for me this was not the culprit. Instead it was the option "deactivate audio" which finally solved the problem.

Disabling the sound did the work for me
Thanks
