### ISSUE TITLE
RDP wont work after last upgrade 1.3.0

### ISSUE THREAD

**Issue by antoweb** [MysticRyuujin/guac-install#167]
Simply disconnected upon connected to a rdp windows server

**Comment by iMrSquare** [comment]
I just had the same problem on Debian.
To solve it I installed the latest beta versions of freerdp2-dev.
For Debian 10.x->
Add repository:
```
apt edit-sources
deb http://deb.debian.org/debian buster-backports main contrib non-free
```
Update:
```
apt update
apt -t buster-backports install freerdp2-dev
```

**Comment by antoweb** [comment]
Thanks there debian 10. I confirm your work solution. Thanks very much

**Comment by aroundmyroom** [comment]
Yep .. this also is working for me under deb10

**Comment by MysticRyuujin** [comment]
I've added a note to the README
