### ISSUE TITLE
disconnect from windows rdp when launch start

### ISSUE THREAD

**Issue by chicco64** [MysticRyuujin/guac-install#170]
Hi !
i tested your script using different operating systems, ubuntu 18.04, debian10, ubuntu 20.10.
The best functioning would seem on ubuntu 20.10 !
Also on this, during the RDP connection, when the "start" button is selected **the connection is interrupted**.
<img width="795" alt="errore_guacamole_2" src="https://user-images.githubusercontent.com/59960414/110204165-9d42d200-7e69-11eb-91f0-24bff4ab0573.PNG">
Same inconvenience if you open the c: \ windows folder
With VNC, on the other hand, everything is regular.
Is it possible to solve this precious inconvenience? thank you

**Comment by durankeeley** [comment]
It's on the README.md

NOTE: Ubuntu users having issues with RDP have reported the following fix:
sudo add-apt-repository ppa:remmina-ppa-team/freerdp-daily
sudo apt-get update
sudo apt-get install freerdp2-dev freerdp2-x11

NOTE: Debian users having issues with RDP have reported the following fix:
sudo bash -c 'echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list.d/backports.list'
sudo apt update
sudo apt -y -t buster-backports install freerdp2-dev libpulse-dev

I had to run this to get my GPG keys after adding the source (I was running debian/raspbian):
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138

**Comment by chicco64** [comment]
Hi,
I did a fresh install on ubuntu 20.04 with the indicated patch, but the error persists.
I'm afraid the problem is the rdp version of my win7
<img width="285" alt="rdp_win7_old" src="https://user-images.githubusercontent.com/59960414/110656128-91cc0f80-81b7-11eb-9ef7-0a014b2c6ac2.PNG">
I tried to control a pc with win10 and the error is not there.
Is it possible to update win7 RDP or install a more current version?
many thanks

**Comment by MysticRyuujin** [comment]
You're saying you can't RDP from your Windows 7 system to your Windows 10 system?

I'd suggest you start here:
https://github.com/MysticRyuujin/guac-install/issues/89#issuecomment-553107254

But Windows 7 is no longer supported by Microsoft so I don't know if it's related or not.

**Comment by durankeeley** [comment]
I made a quick test with a VM, your problem is a Guacamole problem. I changed the setting Disable Glyph Cache and working on my test afterwards

**Comment by chicco64** [comment]
Hi |
wow !!! now it works perfectly with your modification, thanks !!
