### ISSUE TITLE
How to use docker-install.sh?

### ISSUE THREAD

**Issue by ManagerS-IT** [MysticRyuujin/guac-install#172]
How to use docker-install.sh?
For the guac-install.sh file there is a link with wget, but for docker-install.sh I am creating the file by hand with nano.
Is it right or is there something else to be done?

**Comment by MysticRyuujin** [comment]
:smile: 

The static link to the file is `https://raw.githubusercontent.com/MysticRyuujin/guac-install/main/docker-install.sh`

So you could do `wget https://raw.githubusercontent.com/MysticRyuujin/guac-install/main/docker-install.sh`

**Comment by ManagerS-IT** [comment]
Hi, Thanks for the answer, but then he gave some errors.
(The RB4-4GB is with Italian language)
It would appear that MariaDB should be installed instead of MySQL.
But there are other mistakes too


```
pi@RBDMZ:~ $ wget https://raw.githubusercontent.com/MysticRyuujin/guac-install/main/docker-install.sh
--2021-03-15 18:40:44--  https://raw.githubusercontent.com/MysticRyuujin/guac-install/main/docker-install.sh
Risoluzione di raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connessione a raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 3197 (3,1K) [text/plain]
Salvataggio in: "docker-install.sh"

docker-install.sh   100%[===================>]   3,12K  --.-KB/s    in 0,001s

2021-03-15 18:40:44 (4,22 MB/s) - "docker-install.sh" salvato [3197/3197]

pi@RBDMZ:~ $ chmod +x docker-install.sh
pi@RBDMZ:~ $ sudo ./docker-install.sh

Enter a MySQL ROOT Password:
Confirm MySQL ROOT Password:

Enter a Guacamole User Database Password:
Confirm Guacamole User Database Password:

Trovato:1 http://archive.raspberrypi.org/debian buster InRelease
Scaricamento di:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Recuperati 15,0 kB in 3s (5.030 B/s)
Lettura elenco dei pacchetti... Fatto
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze
Lettura informazioni sullo stato... Fatto
Il pacchetto mysql-client non ha versioni disponibili, ma è nominato da un altro
pacchetto. Questo potrebbe indicare che il pacchetto è mancante, obsoleto
oppure è disponibile solo all'interno di un'altra sorgente
Tuttavia questi pacchetti lo sostituiscono:
  mariadb-client-10.0

Il pacchetto docker-ce non ha versioni disponibili, ma è nominato da un altro
pacchetto. Questo potrebbe indicare che il pacchetto è mancante, obsoleto
oppure è disponibile solo all'interno di un'altra sorgente

E: Il pacchetto "docker-ce" non ha candidati da installare
E: Impossibile trovare il pacchetto docker-ce-cli
E: Impossibile trovare il pacchetto containerd.io
E: Impossibile trovare alcun pacchetto tramite il glob "containerd.io"
E: Impossibile trovare alcun pacchetto tramite l'espressione regolare "containerd.io"
E: Il pacchetto "mysql-client" non ha candidati da installare
--2021-03-15 18:42:51--  http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/1.3.0/binary/guacamole-auth-jdbc-1.3.0.tar.gz
Risoluzione di apache.org (apache.org)... 207.244.88.140, 95.216.26.30
Connessione a apache.org (apache.org)|207.244.88.140|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 302 Found
Posizione: https://downloads.apache.org/guacamole/1.3.0/binary/guacamole-auth-jdbc-1.3.0.tar.gz [segue]
--2021-03-15 18:42:52--  https://downloads.apache.org/guacamole/1.3.0/binary/guacamole-auth-jdbc-1.3.0.tar.gz
Risoluzione di downloads.apache.org (downloads.apache.org)... 88.99.95.219, 2a01:4f8:10a:201a::2
Connessione a downloads.apache.org (downloads.apache.org)|88.99.95.219|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 15411981 (15M) [application/x-gzip]
Salvataggio in: "guacamole-auth-jdbc-1.3.0.tar.gz"

guacamole-auth-jdbc 100%[===================>]  14,70M  4,58MB/s    in 3,4s

2021-03-15 18:42:56 (4,37 MB/s) - "guacamole-auth-jdbc-1.3.0.tar.gz" salvato [15411981/15411981]

./docker-install.sh: riga 72: docker: comando non trovato
Waiting for MySQL to be healthy
./docker-install.sh: riga 76: /usr/bin/docker: File o directory non esistente
./docker-install.sh: riga 89: mysql: comando non trovato
./docker-install.sh: riga 91: mysql: comando non trovato
./docker-install.sh: riga 93: docker: comando non trovato
./docker-install.sh: riga 94: docker: comando non trovato

```

**Comment by MysticRyuujin** [comment]
I don't really support Raspberry Pi - nor can I read Italian...

I guess I should fail if the apt-get fails...I can fix that... but it's not clear to be what's failing here.

It looks like first there is a problem with `mysql-client` then there seems to be an issue installing docker, I'm guessing the default pi repositories don't have docker?

**Comment by MysticRyuujin** [comment]
https://phoenixnap.com/kb/docker-on-raspberry-pi

```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

I'm still not sure about the mysql-client error...

**Comment by ManagerS-IT** [comment]
The mysql-client package has no version available, but is named by another
package. This could indicate that the package is missing, out of date
or it is only available within another source
However these packages replace it:
   mariadb-client-10.0

**Comment by ManagerS-IT** [comment]
The docker-ce package has no version available, but is named by another
package. This could indicate that the package is missing, out of date
or it is only available within another source

E: The "docker-ce" package has no candidates to install
E: The docker-ce-cli package could not be found
E: The containerd.io package could not be found
E: Could not find any packages via the glob "containerd.io"
E: Could not find any packages via regular expression "containerd.io"

**Comment by MysticRyuujin** [comment]
You can try to run the script I linked above to install docker and then also run `sudo apt install mariadb-client` as well, then re-execute the script.

**Comment by ManagerS-IT** [comment]
OK.
I read in the readme "I do highly suggest that more people try to use the containerized (docker) version"
And so I used docker-install.
But If you say I didn't keep it up to date, then I'll use guac-install

**Comment by MysticRyuujin** [comment]
I can't test every distro...but I think the latest version of the script should fix your problem

Please try again `wget https://raw.githubusercontent.com/MysticRyuujin/guac-install/main/docker-install.sh`

**Comment by ManagerS-IT** [comment]
I see other errors appear.
How can I remove everything?
So I can use the guac-install script

**Comment by MysticRyuujin** [comment]
What errors? Up until now, nothing has been installed according to your logs.

**Comment by ManagerS-IT** [comment]
First with "sudo sh get-docker.sh" at the end there is a Warning to associate a user to the Docker group.
Also by installing MariaDB-Client, then, by running your script:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
**(This mistake three times)**

Waiting for MySQL to be healthy
ERROR 2013 (HY000): Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)

```
At the end I tried with
https://192.168.203.10:8080/guacamole
Both from a remote PC and from the RB browser
But there is a URL not found error

I also tried with
https://127.0.0.1:8080/guacamole
from the RB browser, but I always get the error.

**Comment by MysticRyuujin** [comment]
Without more logs I can't tell what the problem is. There is a bug (https://github.com/dani-garcia/bitwarden_rs/discussions/1264) that suggests the warning output above might be an issue with docker, and only a warning.

If you run `sudo docker container ls -a` what does it say?

**Comment by MysticRyuujin** [comment]
Ok, I think I know what the problem is ARMv7 is 32bit and there's no support for 32bit. You're going to have to run the normal install script.

**Comment by ManagerS-IT** [comment]
OK. No problem.
But, how can I remove everything?
I would like to avoid installing Raspbian again.

**Comment by MysticRyuujin** [comment]
`mysql` and `mariadb` are not the problem here, the host only needs the `mysql` command line client - which is fixed already by using `default-mysql-client`

To uninstall everything you can simply run `apt remove` for the previously installed components.

**Comment by ManagerS-IT** [comment]
I used guac-install.sh on a freshly installed RB.
This thread should be considered closed.
I open another one for other problems.
Many thanks.
