### ISSUE TITLE
SAML Authentication not workign

### ISSUE THREAD

**Issue by romeogit2021** [MysticRyuujin/guac-install#175]
Hello @MysticRyuujin ,

Thanks for creating this script it really help for beginners like me. I hope you can guide how can i make SAML Authentication work in guacamole. I tried adding guacamole-auth-saml-1.3.0.jar in guacamole_home/extension but its not working i check the logs tomcat logs. I just getting error **no TLDs were found**

**Comment by MysticRyuujin** [comment]
See #121 I'm not sure what is required here but I assume you need to configure a lot more than just adding the extension.
