### ISSUE TITLE
guac-upgrade.sh remote mysql server

### ISSUE THREAD

**Issue by phuongpham** [MysticRyuujin/guac-install#176]
I have used the upgrade script on previous versions.
But I have now move the mysql server to another machine and it's not running local anylonger.
When I run the script even it read the server parameter from guacamole.properties it seems like it still try to connect to localhost after I type in the root password for the sql server.

`user@guacamole:~$ sudo ./guac-upgrade.sh

Enter MySQL ROOT Password:
ERROR 1045 (28000): Access denied for user 'root'@'X.X.X.X' (using password: YES)
`
(Local ip of the same guacamole server)

Does this script support external mysql server?

**Comment by MysticRyuujin** [comment]
https://github.com/MysticRyuujin/guac-install/blob/0816002f0c4a99557fe513029c75d0ca115ea10f/guac-upgrade.sh#L156

It's pulling the `mysqlHost` value from `mysqlHost=$(grep -oP 'mysql-hostname:\K.*' /etc/guacamole/guacamole.properties | awk '{print $1}')`
