### ISSUE TITLE
Error after compilation

### ISSUE THREAD

**Issue by McPwner** [MysticRyuujin/guac-install#179]
Hi there!
I'm not very versed at/in Linux, so I'm sorry in advance for any "n00b" comment.
I have recently used this script couple of times without any problems, it was like revelation for me (thanks dev for it).
Today I tried again, and I have gotten same error repeatedly.
Script was used on VM with Ubuntu Server 20.04.2 with all updates installed (same setup as in past attempts).

This is error message:
![image](https://user-images.githubusercontent.com/72248348/119520336-7fa34b80-bd7a-11eb-8a0b-cd64bf184618.png)

And this is end of the log:

  CC       plugins/libguac_client_rdp_la-channels.lo
  CC       plugins/libguac_client_rdp_la-ptr-string.lo
  CC       libguac_client_rdp_la-pointer.lo
  CC       libguac_client_rdp_la-print-job.lo
  CC       libguac_client_rdp_la-rdp.lo
rdp.c: In function ‘guac_rdp_handle_connection’:
rdp.c:440:5: error: ‘VerifyCertificate’ is deprecated [-Werror=deprecated-declarations]
  440 |     rdp_inst->VerifyCertificate = rdp_freerdp_verify_certificate;
      |     ^~~~~~~~
In file included from /usr/include/freerdp2/freerdp/api.h:23,
                 from /usr/include/freerdp2/freerdp/freerdp.h:42,
                 from beep.h:23,
                 from rdp.c:21:
/usr/include/freerdp2/freerdp/freerdp.h:368:47: note: declared here
  368 |   WINPR_DEPRECATED(ALIGN64 pVerifyCertificate VerifyCertificate); /**< (offset 51)
      |                                               ^~~~~~~~~~~~~~~~~
/usr/include/winpr2/winpr/winpr.h:53:31: note: in definition of macro ‘WINPR_DEPRECATED’
   53 | #define WINPR_DEPRECATED(obj) obj __attribute__((deprecated))
      |                               ^~~
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1329: libguac_client_rdp_la-rdp.lo] Error 1
make[4]: Leaving directory '/home/rdp/guacamole-server-1.3.0/src/protocols/rdp'
make[3]: *** [Makefile:1446: all-recursive] Error 1
make[3]: Leaving directory '/home/rdp/guacamole-server-1.3.0/src/protocols/rdp'
make[2]: *** [Makefile:748: all] Error 2
make[2]: Leaving directory '/home/rdp/guacamole-server-1.3.0/src/protocols/rdp'
make[1]: *** [Makefile:533: all-recursive] Error 1
make[1]: Leaving directory '/home/rdp/guacamole-server-1.3.0'
make: *** [Makefile:455: all] Error 2
 
I should note that I tried with both old and new ppa for FreeRDP, it didn't make difference.

**Comment by MysticRyuujin** [comment]
hmmmmm have you tried WITHOUT using the PPA? Simply running the script and letting it install freerdp from the official sources?

**Comment by McPwner** [comment]
Well, to be honest I did not.  I have always followed instructions and first thing was to manually add PPA as per https://github.com/MysticRyuujin/guac-install#note-ubuntu-users-having-issues-with-rdp-have-reported-the-following-fix

I'll try without adding PPA and will let you know what happened.

**Comment by McPwner** [comment]
Script finished without problem when I didn't add PPA as you suggested.
I'm sorry for taking your time for such silly problem. And thanks again for the script :)
