### ISSUE TITLE
Option or script to install the containerized (Docker) version?

### ISSUE THREAD

**Issue by loosus** [MysticRyuujin/guac-install#182]
The readme file indicates that, going forward, the containerized (Docker) version is recommended over the native version.

I agree with that statement, and I'd really like to use the Docker version.  However, much like the native version, I cannot get it to install without help. (I've tried and not succeeded.)

Is there an option in the script to automatically install the Docker version?  Or is there a separate script to do this?

**Comment by MysticRyuujin** [comment]
I'm not sure I understand the question. There's a docker-install script? What's the problem with either method?

**Comment by loosus** [comment]
I guess the problem is that I didn't know that existed. :) I have been going strictly off the readme file that just mentions the script that appears to install the native version . I'll see if I can find that script you mentioned. Thank you.
