### ISSUE TITLE
RDP is very slow via guacamole

### ISSUE THREAD

**Issue by nsrdev9** [MysticRyuujin/guac-install#187]
Hi,

RDP is very slow to windows 200 R2 when accessing via guacamole. It is working fine with direct RDP client. 
Let me know any suggestions on this issue.

**Comment by dnmartel** [comment]
Hello ! I had the same problem on a Guacamole installation. I found this https://ma.ttias.be/enable-keepalive-connections-in-nginx-upstream-proxy-configurations/ which helped me to solve the problem.
