### ISSUE TITLE
How to Add the Google Auth Module After Script Completion

### ISSUE THREAD

**Issue by Horuyuki** [MysticRyuujin/guac-install#188]
Hello dev!

So the script was very nice and everything works like a dream now. I do want to add the google auth module now that I have decided to expose it over the web. And nginx basic auth just didn't seem to be able to work on the page. Probably because of tomcat and web app layer.

Can I just re-run the script to do that without rebuilding what is already in place, or will I have to rebuild everything and start from scratch by running the script again?

Thanks!

**Comment by MysticRyuujin** [comment]
I would say probably the simplest thing to do is just follow along in the code for the TOTP part and try to just install it after the fact. It's not super complicated...there's a jar file that goes into the extensions folder, and then you run some SQL to update the database scheme and poof TOTP.

**Comment by Horuyuki** [comment]
I see, and would running the script again, thus recompiling everything make it fail?

In other words can I reinstall with the script again in case it breaks because of me messing with it?

**Comment by MysticRyuujin** [comment]
I can't say for sure but it would almost certainly error out or cause issues because it runs SQL commands to setup the database that is already setup...I wouldn't do it lol

You could just wipe and reinstall I guess but then you lose your database.

**Comment by Horuyuki** [comment]
I am fine with losing the database, as long as I can start over clean.

What would I need to wipe? Like some example packages would be nice.

**Comment by MysticRyuujin** [comment]
I peeked at the code, on mobile, but I'm pretty confident that you can simply re-execute the script and it should work... It drops the database if it already exists, etc.

I give it a 80% chance of working lol
