### ISSUE TITLE
Error during installation: cp: call of stat for 'mysql-connector-java-5.1.43/mysql-connector-java-5.1.43-bin.jar' not possible: File or Directory not found

### ISSUE THREAD

**Issue by TheGammelgalopper** [MysticRyuujin/guac-install#19]
Hello Chase,
first of all, thank you for this script! I am kind of new to the linux world and have my problems with general install guides. So no surprise that I can't get my head around the official Guacamole Install Guide. It just says you need this but I have no idea how to get "this"....
So I learn by looking at scripts...
The original error during installation looks like this: 
`
Executing /lib/systemd/systemd-sysv-install enable guacd

cp: Aufruf von stat für 'mysql-connector-java-5.1.43/mysql-connector-java-5.1.43-bin.jar' nicht möglich: Datei oder Verzeichnis nicht gefunden
` 
[Sorry for the wrong language ;)]

This is really strange because I can see that .jar in the script, it should have been downloaded...

When going to the website (IP:8080/guacamole) I just get a blank page but in the Tab it shows the guacamole logo and the hostname...

Pls tell me if you need anything else to help me with this.

**Comment by MysticRyuujin** [comment]
It sounds like you probably failed to download, extract, and move the mysql-connector-java-5.1.43-bin.jar file to /etc/guacamole/lib/

**Comment by TheGammelgalopper** [comment]
Yes but why? When I follow what the script does I can see that it downloads that file and extracts it...

I tried manually downloading that file, extracting and copying it. When I then ran the script again, it gave me the same error...

I also tried just doing the whole script manually, but I can't get the correct download links for the guacamole links as they are behind this little function:

`SERVER=$(curl -s 'https://www.apache.org/dyn/closer.cgi?as_json=1' | jq --raw-output '.preferred|rtrimstr("/")')`

I can't get my head around this...

**Comment by MysticRyuujin** [comment]
Ok so, apache uses a CDN to deliver the files, that line is asking the CDN which server to use...

Run this:
```
SERVER=$(curl -s 'https://www.apache.org/dyn/closer.cgi?as_json=1' | jq --raw-output '.preferred|rtrimstr("/")')
echo $SERVER
```

It should come back with a URL like this:
**http://mirror.olnevhost.net/pub/apache**

That's the prefix/server that you want to download from so this line:
`wget ${SERVER}/incubator/guacamole/${VERSION}-incubating/binary/guacamole-auth-jdbc-${VERSION}-incubating.tar.gz`

Is expanded into this when ran via the complete script:
`wget http://mirror.olnevhost.net/pub/apache/incubator/guacamole/0.9.13incubating/binary/guacamole-auth-jdbc-0.9.13-incubating.tar.gz`

**Comment by TheGammelgalopper** [comment]
So after a while I could look into this again! Thank you for demystifying that function!

The following commands worked for me on Ubuntu 16.04 LTS: (change %password% when repeating this...)

`sudo apt-get update

sudo apt-get upgrade

apt -y install build-essential libcairo2-dev libjpeg-turbo8-dev libpng12-dev libossp-uuid-dev libavcodec-dev libavutil-dev libswscale-dev libfreerdp-dev libpango1.0-dev libssh2-1-dev libtelnet-dev libvncserver-dev libpulse-dev libssl-dev libvorbis-dev libwebp-dev mysql-server mysql-client mysql-common mysql-utilities tomcat8 freerdp ghostscript jq wget curl dpkg-dev

sudo nano /etc/default/tomcat8
# GUACAMOLE ENV VARIABLE
GUACAMOLE_HOME=/etc/guacamole

//mysql new user and database
mysql -u root -p
//enter root %password%
CREATE USER 'guacadmin'@'localhost' IDENTIFIED BY 'guacadmin';
CREATE DATABASE guacamole_db;
GRANT ALL PRIVILEGES ON * . * TO 'guacadmin'@'localhost';
FLUSH PRIVILEGES;
quit


wget http://mirror.23media.de/apache/incubator/guacamole/0.9.13-incubating/source/guacamole-server-0.9.13-incubating.tar.gz
wget http://mirror.23media.de/apache/incubator/guacamole/0.9.13-incubating/binary/guacamole-0.9.13-incubating.war
wget http://mirror.23media.de/apache/incubator/guacamole/0.9.13-incubating/binary/guacamole-auth-jdbc-0.9.13-incubating.tar.gz
wget http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.43.tar.gz

tar -xzf guacamole-server-0.9.13-incubating.tar.gz
tar -xzf guacamole-auth-jdbc-0.9.13-incubating.tar.gz
tar -xzf mysql-connector-java-5.1.43.tar.gz

mkdir -p /etc/guacamole/lib
mkdir -p /etc/guacamole/extensions

cd guacamole-server-0.9.13-incubating
./configure --with-init-dir=/etc/init.d
make
sudo make install
sudo ldconfig
sudo systemctl enable guacd
cd ..

sudo mv -v guacamole-0.9.13-incubating.war /etc/guacamole/guacamole.war
sudo ln -s /etc/guacamole/guacamole.war /var/lib/tomcat8/webapps/
sudo ln -s /usr/local/lib/freerdp/guac*.so /usr/lib/x86_64-linux-gnu/freerdp/
sudo cp -v mysql-connector-java-5.1.43/mysql-connector-java-5.1.43-bin.jar /etc/guacamole/lib/
sudo cp -v guacamole-auth-jdbc-0.9.13-incubating/mysql/guacamole-auth-jdbc-mysql-0.9.13-incubating.jar /etc/guacamole/extensions/

sudo nano /etc/guacamole/guacamole.properties
mysql-hostname: localhost
mysql-port: 3306
mysql-database: guacamole_db
mysql-username: guacadmin
mysql-password: guacadmin
//ctrl+x,y, enter

rm -rf /usr/share/tomcat8/.guacamole
sudo ln -s /etc/guacamole /usr/share/tomcat8/.guacamole

service tomcat8 restart

cat guacamole-auth-jdbc-0.9.13-incubating/mysql/schema/*.sql | mysql -u root -p%password% guacamole_db`

**Comment by MysticRyuujin** [comment]
You either need to modify Tomcat or run it through a proxy server.
