### ISSUE TITLE
Please add support for openSUSE

### ISSUE THREAD

**Issue by radumamy** [MysticRyuujin/guac-install#190]
Could you please add support for openSUSE? There is an official package in openSUSE (e.g. `zypper-aptitude`) that provides compatibility to Debian's aptitude command using zypper. So once this is installed, all apt commands will work as in Debian, so hopefully not much work needed. Thank you.

**Comment by MysticRyuujin** [comment]
So it's not just about having apt, it's also about all of the packages having the same name, or making a list of packages that need to be accounted for. The entire logic behind that is located here:

https://github.com/MysticRyuujin/guac-install/blob/b60850d1b2fa5cd72e9a61d27897e45b654da153/guac-install.sh#L215-L254

If you wanted to do the work to figure it out, I would welcome a PR, however, adding support for another distro is not high on my "want to do" list :smile: 

You could basically just follow the logic of `${NAME} == *"Debian"*` - add whatever openSUSE is to that same logic, and if required...fix the package names...
