### ISSUE TITLE
Adopt to use systemd instead of init.d

### ISSUE THREAD

**Issue by Horuyuki** [MysticRyuujin/guac-install#194]
Guacamole has support for a systemd unit, but the script still defaults to init.d
 
Would the author be so kind to update that portion of the script?

**Comment by MysticRyuujin** [comment]
Feel free to submit a pull request - if I find some motivation to do this on the next release I will but that's a big if :slightly_smiling_face:

**Comment by MysticRyuujin** [comment]
Wasn't as hard as I thought it might be, I guess i'm slightly less lazy than expected.

**Comment by Horuyuki** [comment]
Yes, it was only smth like --systemd flag that is needed.

Thanks for considering the change!
