### ISSUE TITLE
"make" compilation error

### ISSUE THREAD

**Issue by d4rkd3n1337** [MysticRyuujin/guac-install#198]
Hello, I use Ubuntu Server 20.04.2 LTS, and tried installing guacamole with this script.
First of all, I am ran this:
sudo add-apt-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install freerdp2-dev freerdp2-x11

And I ran the install script and it failed, this is how the end of /tmp/guacamole_1.3.0_build.log looks like:

 CC       libguac_client_rdp_la-download.lo
  CC       libguac_client_rdp_la-error.lo
  CC       libguac_client_rdp_la-fs.lo
  CC       libguac_client_rdp_la-gdi.lo
  CC       libguac_client_rdp_la-glyph.lo
  CC       libguac_client_rdp_la-input.lo
  CC       libguac_client_rdp_la-keyboard.lo
  CC       libguac_client_rdp_la-keymap.lo
  CC       libguac_client_rdp_la-log.lo
  CC       libguac_client_rdp_la-ls.lo
  CC       plugins/libguac_client_rdp_la-channels.lo
  CC       plugins/libguac_client_rdp_la-ptr-string.lo
  CC       libguac_client_rdp_la-pointer.lo
  CC       libguac_client_rdp_la-print-job.lo
  CC       libguac_client_rdp_la-rdp.lo
rdp.c: In function ‘guac_rdp_handle_connection’:
rdp.c:440:5: error: ‘VerifyCertificate’ is deprecated [-Werror=deprecated-declarations]
  440 |     rdp_inst->VerifyCertificate = rdp_freerdp_verify_certificate;
      |     ^~~~~~~~
In file included from /usr/include/freerdp2/freerdp/api.h:23,
                 from /usr/include/freerdp2/freerdp/freerdp.h:42,
                 from beep.h:23,
                 from rdp.c:21:
/usr/include/freerdp2/freerdp/freerdp.h:368:47: note: declared here
  368 |   WINPR_DEPRECATED(ALIGN64 pVerifyCertificate VerifyCertificate); /**< (offset 51)
      |                                               ^~~~~~~~~~~~~~~~~
/usr/include/winpr2/winpr/winpr.h:53:31: note: in definition of macro ‘WINPR_DEPRECATED’
   53 | #define WINPR_DEPRECATED(obj) obj __attribute__((deprecated))
      |                               ^~~
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1329: libguac_client_rdp_la-rdp.lo] Error 1
make[4]: Leaving directory '/home/d4rkd3n1337/guacamole-server-1.3.0/src/protocols/rdp'
make[3]: *** [Makefile:1446: all-recursive] Error 1
make[3]: Leaving directory '/home/d4rkd3n1337/guacamole-server-1.3.0/src/protocols/rdp'
make[2]: *** [Makefile:748: all] Error 2
make[2]: Leaving directory '/home/d4rkd3n1337/guacamole-server-1.3.0/src/protocols/rdp'
make[1]: *** [Makefile:533: all-recursive] Error 1
make[1]: Leaving directory '/home/d4rkd3n1337/guacamole-server-1.3.0'
make: *** [Makefile:455: all] Error 2

**Comment by MysticRyuujin** [comment]
NOTE: The fixes below are not to be used UNLESS you're having issues, don't run these for no reason, use the distro maintainers version unless there's a reason not to.

**Comment by sudo-install-ai** [comment]
Has this been fixed? I'm having the same issue.

**Comment by d4rkd3n1337** [comment]
> Has this been fixed? I'm having the same issue.
> 
> 

Yep, just use Debian-Based distr:)

**Comment by sudo-install-ai** [comment]
I really don't mean to waste your time but I'll need a clearer explanation. I'm a complete beginner when it comes to this and have just started my career. Would you mind giving me a longer explanation to follow? I would absolutely appreciate it.

**Comment by d4rkd3n1337** [comment]
> I really don't mean to waste your time but I'll need a clearer explanation. I'm a complete beginner when it comes to this and have just started my career. Would you mind giving me a longer explanation to follow? I would absolutely appreciate it.

So, I have successfully runned and installed Guacamole with this scrilt on Debian 10 and Debian 11 :) Just follow the instructions step by step and everything will work out!

**Comment by sudo-install-ai** [comment]
Hi! I followed all steps and I am still unsuccessful. Note, I am an Ubuntu 20.04 user. Should I be doing something different?

**Comment by d4rkd3n1337** [comment]
> Hi! I followed all steps and I am still unsuccessful. Note, I am an Ubuntu 20.04 user. Should I be doing something different?

So, you can use a ready solution: https://bitnami.com/stack/guacamole
