### ISSUE TITLE
Cannot find the library libguac.la

### ISSUE THREAD

**Issue by wouterVE** [MysticRyuujin/guac-install#21]
I receive 2 errors almost at the end of the installation concerning missing library `libguac.la`

Here is the full output:

```
Making all in src/libguacd
make[2]: Entering directory '/home/Guacomole install/guacamole-server-0.9.13-incubating/src/libguacd'
  CC       libguacd_la-log.lo
  CC       libguacd_la-user.lo
  CC       libguacd_la-socket-ssl.lo
  CCLD     libguacd.la
libtool:   error: cannot find the library 'install/guacamole-server-0.9.13-incubating/src/libguac/libguac.la' or unhandled argument 'install/guacamole-server-0.9.13-incubating/src/libguac/libguac.la'
Makefile:428: recipe for target 'libguacd.la' failed
```

and

```
make[1]: Entering directory '/home/Guacomole install/guacamole-server-0.9.13-incubating/src/libguacd'
  CCLD     libguacd.la
libtool:   error: cannot find the library 'install/guacamole-server-0.9.13-incubating/src/libguac/libguac.la' or unhandled argument 'install/guacamole-server-0.9.13-incubating/src/libguac/libguac.la'
Makefile:428: recipe for target 'libguacd.la' failed
make[1]: *** [libguacd.la] Error 1
```

**Comment by MysticRyuujin** [comment]
You'll have to open an issue with the actual maintainers of Guacamole on this... I don't think that's related to my script?

My first instinct is that maybe it's due to the space in your folder structure, but realistically it should be accounted for in their code... 🤷‍♂️

**Comment by wouterVE** [comment]
Another question: what is the function of the file `guac-install-server.sh` ? 
I've only executed `guac-install.sh` as mentioned in the readme, it's not possible that this is the cause?

**Comment by MysticRyuujin** [comment]
That was written by another contributor, he wanted a script that would only install the guacd service, and not the client side java stuff, I assume for running on separate instances...

**Comment by MysticRyuujin** [comment]
Going to close for now. Can re-open if there's something wrong with the script 😄

**Comment by wouterVE** [comment]
Hello,
Sry for my late reply: I've followed your suggestion and placed the installation folder directly under the root directory. This time I had no problem whatsoever. 
Please note I had ran your updated script and also a week later than my original post. At that time, there were some problems with outdated links so probably that was the cause.

Anyway: problem solved :-)!

thanks a lot!
