### ISSUE TITLE
guac-upgrade.sh fails on MariaDB password

### ISSUE THREAD

**Issue by hardwarejones** [MysticRyuujin/guac-install#24]
- guacamole 0.9.9 on (esxi6.5 vm) Centos7 configured with MariaDB. 
- guac-upgrade.sh asks for mySQL ROOT Password
- when enter MariaDB p/w: fails with ERROR 1049 (42000): Unknown database 'guacamole_db'
- when enter GuacDB p/w: fails with ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by MysticRyuujin** [comment]
Your database isn't called guacamole_db which indicates that you did not install using my script originally or you modified your database name... `Unknown database 'guacamole_db'`

**Comment by MysticRyuujin** [comment]
Sorry, didn't mean to close,

I could probably modify the script to take the database name from the settings file:
`/etc/guacamole/guacamole.properties`

Let me look into doing that

**Comment by MysticRyuujin** [comment]
I made the database name be dynamic, taken from /etc/guacamole/guacamole.properties - that's about all I can do with this issue, if you didn't use my script to install originally then you may need to edit additional paths / variables...

**Comment by hardwarejones** [comment]
No worries; thanks for having a look. 

Cheers
/b
  -----Original Message-----
