### ISSUE TITLE
Update to 1.5.2

### ISSUE THREAD

**Issue by s224105** [MysticRyuujin/guac-install#254]
This tool is awesome, can you please update the script for the 1.5.2 ?
Thx for your work.

**Comment by gauthi3r** [comment]
you can do by yourself directly in the script 

```
# Version number of Guacamole to install
GUACVERSION="1.5.1"
```

Change the version number you want to upgrade.

I have test it few days ago but i have note some latency in connexion ssh or rdp.
i rolling back to 1.5.1 for the moment.

Debian 12 isn't supported yet according to my first tests.

**Comment by s224105** [comment]
Thx for the answer i didn't know it was that simple.
 :)
