### ISSUE TITLE
Error installing on Ubuntu 16.04.3 Raspberry pi:

### ISSUE THREAD

**Issue by SaintFenix** [MysticRyuujin/guac-install#27]
I've got a pastebin here:
https://pastebin.com/4a9UT1ny

The issue I see is that at line 70. the script calls for:
http://mirror.jax.hugeserver.com/apache/guacamole/16.04.3

appending my OS version onto the end which doesn't exist on the mirrors, I'm really not the best at this, and am playing around with it, so it may be inexperience.

But if there is any help available, I would be very grateful for it.

**Comment by MysticRyuujin** [comment]
Your issue is the same as #26 I think, I'm an idiot, but I think I fixed it?

**Comment by SaintFenix** [comment]
you're a smarter idiot than me. :)

The change did change my output, same result however:

https://pastebin.com/TPCTeT3H

line .62 same issue, from what I'm reading it's trying to pull a guacamole version that is equivalent to 16.04.3 though the version numbering for guacamole only goes up to 9.14.

I'm awful as scripting, but I think I'm following where it gets screwed up.

and thanks, I do appreciate the help.

**Comment by SaintFenix** [comment]
That right there is some quality fixin. :) You got it fixed, and it runs beautifully on my pi now.

Thank you for the work, and doing it so quick. You deserve more praise than you seem to be getting.

I'll spread word of this script far and wide.
