### ISSUE TITLE
guac-upgrade wont finish with duo setup

### ISSUE THREAD

**Issue by nayra42** [MysticRyuujin/guac-install#29]
So, I set up Guacamole with your .9.13 script and then added Duo MFA.  I now tried to do the upgrade script and then put the new version of duo on there but it still will only launch .9.13.  Ideas?

**Comment by MysticRyuujin** [comment]
So, I was having that problem too and I couldn't figure out why...

Try downloading the .war file again and overwriting the /etc/guacamole/guacamole.war file again then restart tomcat...

That seemed to work for me but I don't know why...

**Comment by nayra42** [comment]
Yeah that did it, but, i had to run the script again, restarting tomcat was not enough.  Dunno, but thank you!

**Comment by MysticRyuujin** [comment]
Closing for now
