### ISSUE TITLE
In Debian (and maybe Ubuntu), use the mySQL connector package instead of sources

### ISSUE THREAD

**Issue by MagicFab** [MysticRyuujin/guac-install#30]
In Debian there is a working mySQL connector package. Instead of using sources the script could use the package. It also needs to be linked appropriately:

```
# apt install libmysql-java
# ln -s /usr/share/java/mysql-connector-java.jar /etc/guacamole/lib/
```

The package version in Debian Stretch is 5.1.42-1, though, so this is older and needs to be considered if the latest version solves any bug directly affecting Guacamole features.

**Comment by MysticRyuujin** [comment]
I guess I don't understand the "issue?" you're asking me to use the package maintainer's version instead of just downloading the latest? What's the benefits here?

**Comment by MagicFab** [comment]
The main benefit is automatic updates.

**Comment by MysticRyuujin** [comment]
Like 5.1.42-1 automatic or? 😆 

My update script is generally updated to include the latest version, so I don't see the point...

**Comment by MysticRyuujin** [comment]
So the guacamole documentation, which is what I base all of this on, specifically says:

`The MySQL JDBC driver is not included with the extension. You must obtain the JDBC driver .jar yourself from MySQL's website. The driver is known as "Connector/J", and the required .jar will be within a .tar.gz archive.`

I guess I don't actually prefer one way over the other, except that the complexity of updating this jar file yourself is basically zero...I'd prefer to stick with what the documentation says and maintain the latest version in my script because 5.1.42 is almost a year old and there are a number of bug fixes between .42 and .45 - and Guacamole seems to be working fine on the latest.

**Comment by MagicFab** [comment]
Yes, automatic, stable updates when possible, aiming at long term support. I prefer, as much as possible, not to update manually OS main components that are already packaged and can have long term support.

Version 5.1 is a [general availability (GA) release](https://dev.mysql.com/doc/mysql-development-cycle/en/ga-releases.html) recommended for production systems, [8.0 is still in Developer Milestone status and is not yet ready for use in a production environment](https://dev.mysql.com/doc/mysql-development-cycle/en/ga-releases.html). Guacamole documentation seems written only for development purposes in that context.

Having the latest development version updated from sources is not best practice - this was just a suggestion to improve the script, much like you did with Tomcat (which is the opposite situation, preferring a supported release to an EOL release).

**Comment by MysticRyuujin** [comment]
I only use the current most up to date GA release in the script and in the upgrade script. I know where you're coming from but this script isn't for corporate or enterprise use, it's for average users who want an easy way to install Guacamole...and I feel better about using the latest version that I know works than relying on the package maintainers to update or not update as they see fit. Anyone actually worried about stable long term support can fork and/or edit that part of the code 😄 

If you want you can submit a pull request that prompts the user for which they would like to installed (latest, manually, or through the package maintainer's version) I'd totally support that 👍

**Comment by MysticRyuujin** [comment]
idk maybe you're right, maybe it's easier to just do the apt way... I suppose it would take the onus off me to go check the latest versions and test. I'd probably just run into the same issue where it's called something different on different distros 👎

**Comment by MagicFab** [comment]
It is simpler, but you're right currently both Debian and Ubuntu are behind a couple of versions. They can't always have the very latest as per their support/release schedules.

So yeah, having the choice would be ideal, this is really nitpicking on my part if I'm honest. :) Until Guacamole is 100% packaged in Debian this scripts remains the most support-able option.

I think it's enough for me that this report is available, I didn't know about GA vs. dev versions before. I filed a few bugs in Debian to improve official support for next releases but agree the decision on using this in production installing from sources is not hard at the moment (give the alternatives).

**Comment by MysticRyuujin** [comment]
Apparently this is now broken in 19.10 as this library isn't available?

**Comment by MysticRyuujin** [comment]
Track in #108
