### ISSUE TITLE
guacd compile fail on ubuntu server 17.10

### ISSUE THREAD

**Issue by zdomokos** [MysticRyuujin/guac-install#32]
When compiling guacd error message:
typescript.c:133:46: error: ‘%s’ directive writing 6 bytes into a region of size between 0 and 2047 [-Werror=format-overflow=]
     sprintf(typescript->timing_filename, "%s.%s", typescript->data_filename,
                                              ^~
In file included from /usr/include/stdio.h:862:0,
                 from typescript.c:28:

This is most likely from gcc7 see here: http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Raspberry-Pi3-Debian-compile-fails-for-Stable-and-git-versions-of-Guacamole-server-td1598.html

**Comment by MysticRyuujin** [comment]
¯\_(ツ)_/¯

**Comment by narabug** [comment]
Had the same issue - had to do additional research to resolve.

If the OS version if Ubuntu 17+, this script block needs to execute to revert to gcc6 compiler:

`sudo apt-get remove gcc g++
sudo apt-get update && \
sudo apt-get install build-essential software-properties-common -y && \
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
sudo apt-get update && \
sudo apt-get install gcc-snapshot -y && \
sudo apt-get update && \
sudo apt-get install gcc-6 g++-6 -y && \
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6`

**Comment by zdomokos** [comment]
Getting guacd source from github worked.
Here is the script:

![image](https://user-images.githubusercontent.com/2656974/37261579-2295bed8-2574-11e8-8068-e24671315c11.png)

**Comment by MysticRyuujin** [comment]
#38

**Comment by jonasstaehle** [comment]
For everyone still confused on Ubuntu 17.XX:

1. Install gcc-6

`sudo apt install gcc-6 g++-6`

2. Run make with gcc-6 compiler:

`make CC=gcc-6`
