### ISSUE TITLE
Newest docker engine is called differently

### ISSUE THREAD

**Issue by djpbessems** [MysticRyuujin/guac-install#42]
Probably you should replace 
https://github.com/MysticRyuujin/guac-install/blob/169058d029a873ee6a1db2354aa6d535338576df/docker-install.sh#L53
with
`apt-get -y install docker-ce mysql-client wget`

**Comment by MysticRyuujin** [comment]
Do you know if docker-ce is available on all or most distros? I'd hate to change it and then have more people opening issues because it's not available on their distro 👎

**Comment by djpbessems** [comment]
`docker.io` is deprecated (was debian/ubuntu specific anyway).
See https://p.itch.fyi/t2NpiG
