### ISSUE TITLE
Include reverse proxy configuration?

### ISSUE THREAD

**Issue by e-alfred** [MysticRyuujin/guac-install#43]
Hello,

it would be great to have a reverse proxy configuration (Apache or NGINX) included to make the installation easier and more secure. Currently the Guacamole server can be reached over HTTP directly which is not ideal for secure remote connections.

Awesome script by the way, great work!

**Comment by MysticRyuujin** [comment]
FYI: I do have a blog post on my website http://www.chasewright.com just search NGINX
