### ISSUE TITLE
Error in configure

### ISSUE THREAD

**Issue by machstem** [MysticRyuujin/guac-install#45]
I ended up using your script on Linux Mint, adjusted the os-version check and replaced the Ubuntu with Linux Mint.  Everything works until it attempts to configure the guacamole-server-0.9.14 package.  I get the following error:

> make[2]: Entering directory '/home/machstem/guacamole-server-0.9.14/src/terminal'
>   CC       libguac_terminal_la-typescript.lo
> typescript.c: In function ‘guac_terminal_typescript_alloc’:
> typescript.c:133:46: error: ‘%s’ directive writing 6 bytes into a region of size between 0 and 2047 [-Werror=format-overflow=]
>      sprintf(typescript->timing_filename, "%s.%s", typescript->data_filename,
>                                               ^~
> In file included from /usr/include/stdio.h:862:0,
>                  from typescript.c:28:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 8 and 2055 bytes into a destination of size 2048
>    return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>        __bos (__s), __fmt, __va_arg_pack ());
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> Makefile:566: recipe for target 'libguac_terminal_la-typescript.lo' failed
> make[2]: *** [libguac_terminal_la-typescript.lo] Error 1
> make[2]: Leaving directory '/home/machstem/guacamole-server-0.9.14/src/terminal'
> Makefile:503: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/machstem/guacamole-server-0.9.14'
> Makefile:427: recipe for target 'all' failed
> make: *** [all] Error 2

I get the same error when I run the configure command manually, and was wondering if you had any ideas on how to help.

Thanks

**Comment by machstem** [comment]
I succesfully used make by adjusting it to use:  make CC=gcc-6

**Comment by MysticRyuujin** [comment]
Pretty sure this is fixed now because of the patch
