### ISSUE TITLE
Initial guac-install.sh script error

### ISSUE THREAD

**Issue by awasney** [MysticRyuujin/guac-install#46]
![image](https://user-images.githubusercontent.com/42870838/44918833-f023f780-ad09-11e8-82fd-be4be6e40535.png)

**Comment by awasney** [comment]
I get the following error when trying to install the script

**Comment by MysticRyuujin** [comment]
What OS?

**Comment by awasney** [comment]
18.04


Should I only use 16.04?


Andrew

**Comment by MysticRyuujin** [comment]
What happens when you run 'apt update'?

**Comment by awasney** [comment]
I'm doing this on a VM, so I went back to 16.04 as you recommended and it's working fine.  My mistake.  Thank you for your assistance.

**Comment by MysticRyuujin** [comment]
I generally think it should work on 10.04, I wasn't suggesting you to downgrade for my behalf 😄 I know that when I create an Ubuntu VM using VMWare Workstation they they hose up the apt source list to point to a CDROM and I usually have to go comment that out for the apt function to work, that' s why I asked.

Sorry for the bluntness of my previous replies, I was busy at work.

**Comment by awasney** [comment]
Totally fine! I completely understand.  Thank you.


Andrew
