### ISSUE TITLE
Execution of guac-install.sh ends in a failure

### ISSUE THREAD

**Issue by bmullan** [MysticRyuujin/guac-install#47]
I am trying to run guac-install.sh on ubunu 18.04 but near the end of the script during the "make" there is a warning/error and the msg that all warnings being treated as errors"

Any idea what might be causing this error as I don't see anyone else reporting it?
thanks
brian

> typescript.c: In function ‘guac_terminal_typescript_alloc’:
> typescript.c:133:46: error: ‘%s’ directive writing 6 bytes into a region of size between 0 and 2047 [-Werror=format-overflow=]
>      sprintf(typescript->timing_filename, "%s.%s", typescript->data_filename,
>                                               ^~
> In file included from /usr/include/stdio.h:862:0,
>                  from typescript.c:28:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 8 and 2055 bytes into a destination of size 2048
>    return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>        __bos (__s), __fmt, __va_arg_pack ());
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> **cc1: all warnings being treated as errors**
> Makefile:566: recipe for target 'libguac_terminal_la-typescript.lo' failed
> make[2]: *** [libguac_terminal_la-typescript.lo] Error 1
> make[2]: Leaving directory '/opt/ciab/guacamole-server-0.9.14/src/terminal'
> Makefile:503: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/opt/ciab/guacamole-server-0.9.14'
> Makefile:427: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by MysticRyuujin** [comment]
Try `make CC=gcc-6`

**Comment by bmullan** [comment]
its using gcc-6 already

**Comment by MysticRyuujin** [comment]
Yeah, that's strange...I made the gcc hack specifically because people were saying it stopped working and that using gcc-6 would fix it.

Unfortunately I do not know how to do either of these things suggested off the top of my head:

```
- Grab the code from the pull request above and patch the 0.9.14 version of the code.
- Stick with 0.9.14 and install with a compiler that is known to work.
``` 

So I guess 18.04 is borked for now until 1.0 comes out or someone figure out a quick fix 👍

**Comment by bmullan** [comment]
Chase

I did send Nick an email asking if there was any way to include the fix
back into Guac 0.9.14.   I told him that during the past day or so while I
was
searching for a solution I found a long thread of redhat users that were
trying to get guacamole built and hitting this bug and they were blaming it
on the version of gcc, various libraries, their distro.   I told him I saw
the same with debian & ubuntu users threads on it as well.

I also mentioned that:

   - many/most of these users would NOT know how to "git" the v1.0 master
   branch & build from it
   - many people use 3rd party scripts to build/install guacamole and are
   probably now questioning whether guacamole really works or not
   - that none of the users have any idea when the v1.0 might become
   available


So maybe he will try to add the fix back into v0.9.14 ?

Brian

**Comment by bmullan** [comment]
Chase

Got a reply back from Nick and basically v1.0 is just a couple weeks from
release.

but one thing he did say was that if someone manually applies the fix to
the v0.9.14

this is the pull (# 150) that shows the code that needs to be changed...
and it does look like a simple change.

https://github.com/apache/guacamole-server/pull/150/commits

brian

**Comment by MysticRyuujin** [comment]
I have to be honest, I don't know how to download the source zip, extract it, then overwrite the specific file with that specific git pull 😄

I could try sed maybe...

**Comment by bmullan** [comment]
For myself I'm probably going to just wait for 1.0

But using the 2 cmds Nick sent should be easy w your script.

Before you run your script download the guac source as a zip.

Unzip it in the same directory you will eventually run your script from.

Then run those 2 patch commands Nick sent that wiil patch src/terminal/typeface.c

Then temporarily edit your script and just comment out the line that does the wget and the one that does the tar -xvf

Then you should be able to run your script which will buid against your already patched typeface.c

Seems to me that should work ok

**Comment by bmullan** [comment]
Chase
I just did what I basically described in the last msg.

**STEP 1**

Before I ran your script I manually ran the wget for the guacamole server tar.gz by creating a little script.

> #!/bin/bash
> # Set SERVER to be the preferred download server from the Apache CDN
> SERVER="http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/0.9.14"
> 
> # Download Guacamole Server
> wget -q --show-progress -O guacamole-server-0.9.14.tar.gz ${SERVER}/source/guacamole-server-0.9.14.tar.gz

**STEP 2**
Put that script into the **same** directory as your script which should be the same directory you execute your script in.

**STEP 3**
Execute the new script

**STEP 4**
Apply the patch using the 2 commands

**NOTE 1**: the following wget is all 1 line

**wget https://github.com/apache/guacamole-server/commit/cd0e48234a079813664052b56c501e854753303a.patch

patch -p1 < cd0e48234a079813664052b56c501e854753303a.patch**

**NOTE 2**: upon executing the "patch" command it will ask you "what file to patch" and you will have to specify the complete path (assuming your are in the directory where you will be executing "your" script then that filename/path that you should enter should be:

 guacamole-server-0.9.14/src/terminal/typescript.c

The patch only takes 2 seconds and its done

**STEP 5**

Edit your guac-install.sh

and comment out the section where your script downloads (wget) the server code because you don't want to download it again and overwrite the patch you just made !

> # Download Guacamole Server
> # wget -q --show-progress -O guacamole-server-${GUACVERSION}.tar.gz ${SERVER}/source/guacamole-server-${GUACVERSION}.tar.gz
> #if [ $? -ne 0 ]; then
> #  echo "${RED}Failed to download guacamole-server-${GUACVERSION}.tar.gz"
> #  echo "${SERVER}/source/guacamole-server-${GUACVERSION}.tar.gz"
> #  exit
> # fi

**STEP 6**

Execute your script and it should now complete the build successfully (mine did).

**Comment by MysticRyuujin** [comment]
Alright I ran it start to finish on a fresh 18.04 install. Closing.
