### ISSUE TITLE
suggest addition to guac-install.sh

### ISSUE THREAD

**Issue by bmullan** [MysticRyuujin/guac-install#48]
As sudo/root privilege is required to execute guac-install.sh maybe adding the following to the top of the script would save people who didn't read the instructions from wondering why their execution of guac-install.sh fails...

The following will check if the script was executed as sudo or root and if not warn the user with the message and just terminate the script execution without going further...

> \# Check if user is root or sudo
> if ! [ $(id -u) = 0 ]; then echo "Please run this script as sudo or root"; exit 1 ; fi

**Comment by MysticRyuujin** [comment]
I'll add it, you could have made a pull request...

**Comment by bmullan** [comment]
I would of but I've never done it before

Sorry
