### ISSUE TITLE
Add support for Ubuntu derivatives

### ISSUE THREAD

**Issue by dashohoxha** [MysticRyuujin/guac-install#52]
I have tested it on LinuxMint and it works flawlessly.
However this line: https://github.com/MysticRyuujin/guac-install/blob/master/guac-install.sh#L74
needs to be fixed to something like this:
```bash
if [[ "${NAME}" == "Ubuntu" || ${ID_LIKE} == "ubuntu" ]]
```

Also this line: https://github.com/MysticRyuujin/guac-install/blob/master/guac-install.sh#L77
needs to be fixed to something like this:
```bash
if [[ $UBUNTU_CODENAME == 'bionic' ]]
```
and the next "if" can be changed to:
```bash
if [[ $UBUNTU_CODENAME == 'xenial' ]]
```

**Comment by MysticRyuujin** [comment]
Submit a pull request :smile:
