### ISSUE TITLE
Make installation customizable

### ISSUE THREAD

**Issue by dashohoxha** [MysticRyuujin/guac-install#53]
Instead of having several installation scripts like `guac-install.sh`, `guac-install-server.sh`, `guac-install-totp.sh`, `guac-totp-ssl.sh`, etc. (from https://github.com/MysticRyuujin/guac-install/pull/41/files) make a single script that can be customized.

* Customization can be done by using options (for example: `./guac-install.sh --server-only --totp --ssl --version=0.9.14`).

* Or it can be done by including a file of settings (`source ./settings.sh`), with a content like this:
```bash
VERSION="0.9.14"    # it can also be "master" or another git branch
SERVER_ONLY="yes"
TOTP="yes"
SSL="yes"
MYSQL="yes"
```

* Another way of refactoring the code can be by using a library of common functions (for example `common.sh`) which is included on each of the scripts (`guac-install.sh`, `guac-install-server.sh`, `guac-install-totp.sh`, `guac-totp-ssl.sh`, etc.) and then the appropriate/relevant functions are called.

**Comment by MysticRyuujin** [comment]
My level of effort put into this repo is minimum to keep it working for myself. I didn't even create the server-only file. I just try to keep it somewhat current, and I usually fail at that too.

As much as I agree that this stuff could be done, I'm not going to take the time to actually do it. For me, it has one purpose, quickly deploy a new guac instance on my Ubuntu servers.

I'm happy to merge code that people submit and I occasionally cater to people's requests to fix something here and there, but I don't have the energy to refactor all that...not now anyway...personally I wish the guacamole team would just do a ppa  or deb or an rpm...and I wouldn't have to maintain this...lol

**Comment by dashohoxha** [comment]
That's fine. However it seems that you have already made a great effort for making it easy for other people too (for example nice messages, getting mysql password as an option from commandline or interactively). When you do a script for your personal needs you just keep it simple (for example get the mysql password the same way that you get the guacamole version).

Anyway, this is a useful script. Thanks for sharing it.

You may keep this issue open as a feature request, in case someone wants to implement it.

> personally I wish the guacamole team would just do a ppa or deb or an rpm...and I wouldn't have to maintain this

There is already a deb package for guacamole, but it is too old. Packaged versions are always too old. And packed versions cannot solve all the problems (for example do you want MySQL authentication, or LDAP, or OpenID, etc.)

**Comment by MysticRyuujin** [comment]
Actually the pretty messages and nice output was also a pull request that I just tried to maintain haha

**Comment by dashohoxha** [comment]
> There is already a deb package for guacamole, but it is too old.

Actually there are packages `guacamole` and `guacd` on Debian, not Ubuntu. Sorry about that. They install guacamole-0.9.9, which is a bit old.

> Actually the pretty messages and nice output was also a pull request that I just tried to maintain

My opinion is that a script does not need that kind of prettiness, especially when it comes at the expense of obscuring the source code. Your script was very useful for me because I could see how you fix the problems. I could have spent a very long time myself and even give up, if I could not make it work. But the code that provides prettiness just obscures the real code for me and makes it more difficult to read and understand. My script does not include that kind of things on purpose:
https://gitlab.com/Virtual-LTSP/VirtualBox/blob/bionic/ltsp-server/scripts/guacamole.sh

So, thanks again for writing and maintaining these scripts. They have been very useful.
