### ISSUE TITLE
Cant login after fresh install

### ISSUE THREAD

**Issue by Rexima** [MysticRyuujin/guac-install#58]
I have a fresh ubuntu 18.04 and debian 9.4 vm setup.
And after using your install script, i try to login to the backend but without success.

I use guacadmin/guacadmin and after i press the login button i got redirected to the login page again.
When i left both inputs blank, i got an authentication error.

**Comment by dwarfmage** [comment]
Any fix for this? I've tried a fresh ubuntu 18.04.1 server install and run the guac-install.sh twice now with the same problem. guacadmin/guacadmin redirects back to the login page

**Comment by MysticRyuujin** [comment]
Post the log and output?

`LOG="/tmp/guacamole_${GUACVERSION}_build.log"`

**Comment by dwarfmage** [comment]
[guacamole_install.txt](https://github.com/MysticRyuujin/guac-install/files/2824351/guacamole_install.txt)
[guacamole_1.0.0_build.log](https://github.com/MysticRyuujin/guac-install/files/2824352/guacamole_1.0.0_build.log)

**Comment by dwarfmage** [comment]
Apologies. It is a config issue with my workstation. Using a different machine allows me to log on correctly.
