### ISSUE TITLE
Script for RHEL

### ISSUE THREAD

**Issue by riahc3** [MysticRyuujin/guac-install#61]
Why is this avaliable for Ubuntu (of all platforms)....

Either Debian (which I imagine this script works on) or RHEL/CentOS. Dont lose time on Ubuntu.

**Comment by riahc3** [comment]
Closed? Why?

**Comment by bmullan** [comment]
@riahc3 - that's a pretty crappy attitude IMO.  I don't often see people bad mouthing RHEL or CentOS like that?

**Comment by riahc3** [comment]
> @riahc3 - that's a pretty crappy attitude IMO. I don't often see people bad mouthing RHEL or CentOS like that?

I ment that Ubuntu is a more consumer OS; You dont see many servers running Ubuntu....Either Debian or RHEL.

Was something else understood???

**Comment by MysticRyuujin** [comment]
If you want a script that supports RHEL, make one. Fork this and have at it. Submit a pull request. Otherwise, I'm just a random dude who wanted to install Guacamole on my home system and help others to do the same. You can take your attitude and gtfo. I don't owe you anything, especially my time.

**Comment by bmullan** [comment]
@riahc3 - This comment is not to disparage RHEL or CentOS (I've used both and live 3 miles from Red Hat's headquarters & have many friends working there.

But in your statement on usage in the commercial world I think you are mistaken.

I've used AWS, Digital Ocean and a couple other clouds for quite a few years now so I just went out and logged into AWS EC2 and here are the current Stats for the number of AMI's (Amazon Machine Image) for RHEL, CentOS, Debian and Ubuntu as of 4:10pm EST Jan 10, 2019

from queries via:
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:

> RHEL    -   2,241
> CentOS -   2,294
> Debian  -   8,115
> Ubuntu  - 30,197

Of course that's just Publicly available AMI's but it gives you an idea of utilization of each Distro on AWS's cloud.

Digital Ocean's cloud show's much the same numbers.

Ubuntu is heavily used commerically.   OpenStack, OpenNebula, Docker, NextCloud are just examples of a few of the systems/applications designed & tested on Ubuntu.

Of course Ubuntu owes much to Debian obviously but I just wanted you to know another side of the story.

**Comment by riahc3** [comment]
@bmullan - Those stats that your pulled are true BUT...they are used by non-professionals who just click "Next" and share their data.

RHEL/CentOS administrators basically block their data or their infrastructure is DMZd. RHEL is used worldwide at enterprise level.

@MysticRyuujin  - I dont understand where that attitude came from. I was just suggesting a script for RHEL...

**Comment by riahc3** [comment]
@MysticRyuujin - Well, sorry about the wording. Ive made it a bit clearer in here: https://github.com/MysticRyuujin/guac-install/issues/63 

Thank you.

**Comment by bmullan** [comment]
@riahc3
Some reading for you

https://www.linux.com/blog/2019/1/top-5-linux-distributions-development-2019

**Comment by riahc3** [comment]
@bmullan  Fedora is RHEL
