### ISSUE TITLE
Please clarify FreeRDP 2 support in Debian / Ubuntu

### ISSUE THREAD

**Issue by MagicFab** [MysticRyuujin/guac-install#64]
Thank you for your work on this script, I see it's been updated for the latest Guacamole release 1.0.0 !

I'd like to know if it supports FreeRDP 2 (rc4?) since previous versions could not build against it and FreeRDP 1 is being dropped in Debian.

There is ongoing discussion about supporting FreeRDP2 in Guacamole at [Debian no. 90047](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900447) and [Guacamole JIRA no. 249](https://issues.apache.org/jira/browse/GUACAMOLE-249).

**Comment by MysticRyuujin** [comment]
My script simply installs the required and optional dependencies listed in the guacamole manual and instructions. I have no idea and I'm not associated with Guacamole project in any way.
