### ISSUE TITLE
404 when accessing webapp

### ISSUE THREAD

**Issue by cyoder4400** [MysticRyuujin/guac-install#65]
This was installed on Debian 8.3. Tomcat logs show error: 

Error configuring application listener of class org.apache.guacamole.GuacamoleServletContextListener
java.lang.UnsupportedClassVersionError: org/apache/guacamole/GuacamoleServletContextListener : Unsupported major.minor version 
52.0 (unable to load class org.apache.guacamole.GuacamoleServletContextListener)

Verified the .war file was in the correct location, port 8080 was open, and Tomcat was running and responding to web requests.

**Comment by MysticRyuujin** [comment]
What version of Java you got?

Java 8 or later is now required

**Comment by cyoder4400** [comment]
Java 8.201

**Comment by pablopol24** [comment]
The same thing happened to me after updating with the script from 0.9.14 to 1.0.0, ubuntu 16.04

**Comment by MysticRyuujin** [comment]
I removed the GCC7 hack from the script(s) can you re-run the upgrade script?

**Comment by cyoder4400** [comment]
Attempted it again and same results. Even ran this on a second fresh Debian 8.3 install just to make sure I didn't have anything blocking it and same result.
