### ISSUE TITLE
Error Login  update 1.0.0

### ISSUE THREAD

**Issue by pablopol24** [MysticRyuujin/guac-install#66]
Hello
I have the version 0.9.14 installed by script to update it to 1.0.0 with the same method I do not see the login screen.
What can be ?

Ubuntu 16.04, openjdk version "1.8.0_191"

**Comment by MysticRyuujin** [comment]
I removed the GCC7 hack from the script(s) can you re-run the upgrade script?

**Comment by pablopol24** [comment]
I regret not being able to prove it, for a matter of time I decided to install 0. Now it works perfect.
