### ISSUE TITLE
Cannot load guacamole-auth-jdbc-mysql-1.0.0.jar after 9.4.0 => 1.0.0 upgrade

### ISSUE THREAD

**Issue by coom** [MysticRyuujin/guac-install#67]
Hello,

Used your script to install 0.9.4 and then used your script to update to 1.0.0, login web page correctly displayed but unable to login.

In my catalina.out I can see :
```
11:33:20.905 [localhost-startStop-1] ERROR o.a.g.extension.ExtensionModule - Extension "guacamole-auth-jdbc-mysql-1.0.0.jar" could not be loaded: Authentication provider class cannot be loaded (wrong version of API?).
```

Do you have an idea ? Thanks in advance and please excuse my english :)

**Comment by MysticRyuujin** [comment]
I removed the GCC7 hack from the script(s) can you re-run the upgrade script?

**Comment by joBr99** [comment]
I've sucessfully upgraded from 0.9.4 to 1.0.0 on Ubuntu 18.04.1 LTS with the guac-upgrade script.
