### ISSUE TITLE
Error com.mysql.jdbc.exceptions with guac-install 1.0.0

### ISSUE THREAD

**Issue by m4xx75** [MysticRyuujin/guac-install#70]
Hello,

First, congratulations and thank you for your work!
I encounter an error after a fresh install of 1.0.0 on Ubuntu server 18.04.1 :
```
19:47:55.966 [http-nio-8080-exec-2] ERROR o.a.g.rest.RESTExceptionMapper - Unexpected internal error:
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
```
Thanks in advance,
maxx

**Comment by m4xx75** [comment]
up

**Comment by areynolds77** [comment]
Try changing the 'mysql-hostname' parameter in '/etc/guacamole/guacamole.properties' from 'localhost' to '127.0.0.1'. Per [https://serverfault.com/questions/306421/why-does-the-mysql-command-line-tool-ignore-the-port-parameter](this serverfault question) when you use 'localhost' the mysql client attempts to connect via a socket as opposed to a port.

**Comment by m4xx75** [comment]
> Try changing the 'mysql-hostname' parameter in '/etc/guacamole/guacamole.properties' from 'localhost' to '127.0.0.1'. Per [this serverfault question](https://serverfault.com/questions/306421/why-does-the-mysql-command-line-tool-ignore-the-port-parameter) when you use 'localhost' the mysql client attempts to connect via a socket as opposed to a port.

Thank you very much, it works!
Unfortunately I have a new problem ... I am going to open a new issue.
maxx
