### ISSUE TITLE
(Ubuntu 18.04 Server) Upgrade script did not install latest guacamole.war client file

### ISSUE THREAD

**Issue by mrosun** [MysticRyuujin/guac-install#73]
I've only been using your install scripts to run Guacamole up and I noticed an issue.

Logs showed:

`Creation of WebSocket tunnel to guacd failed: Connection to guacd timed out.`
and
`Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of libguac?`

The upgrade script did not install the latest guacamole-1.0.0.war file in the /etc/guacamole folder.

I had to manually download it, replace the old one and remake the link from /var/lib/tomcat8/webapps/guacamole.war to point to it.

I hope this helps.

**Comment by MagicFab** [comment]
What GNU/Linux distribution were you using ? Can you update the title to reflect this ?

**Comment by MysticRyuujin** [comment]
I think this was fixed?
