### ISSUE TITLE
issue with building

### ISSUE THREAD

**Issue by asdlkf** [MysticRyuujin/guac-install#74]
I tried running this script today on Ubuntu 18.10 and the install is broken.

I tried:

- fresh ubuntu 18.10 install ISO
- apt-get update
- apt get upgrade
- reboot the VM
- download the script file
- chmod +x
- run the script file
- provide passwords

...
...
`make[2]: Entering directory '/home/username/guacamole-server-1.0.0/src/guacenc'
  CC       guacenc-guacenc.o
guacenc.c: In function ‘main’:
guacenc.c:79:5: error: ‘avcodec_register_all’ is deprecated [-Werror=deprecated-declarations]
     avcodec_register_all();
     ^~~~~~~~~~~~~~~~~~~~
In file included from guacenc.c:27:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4086:6: note: declared here
 void avcodec_register_all(void);
      ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:761: guacenc-guacenc.o] Error 1
make[2]: Leaving directory '/home/username/guacamole-server-1.0.0/src/guacenc'
make[1]: *** [Makefile:510: all-recursive] Error 1
make[1]: Leaving directory '/home/username/guacamole-server-1.0.0'
make: *** [Makefile:432: all] Error 2
`

I managed to get the script to work with:

`export CFLAGS="-Wno-error"`

Unsure of the impact of installing like this.

**Comment by MysticRyuujin** [comment]
Yup, Guacamole on 18.10 is broken. This is a problem with the guacamole make files and there's an open issue for it somewhere on the Guacamole JIRA / Forms. Unfortunately there's nothing I can do about it that I'm aware of... If someone finds a solution I can automate into the script I'd be happy to accommodate but I don't have a lot of time to dig into it.

The only suggestion I have is use 18.04 if you want to use the script for now
