### ISSUE TITLE
Migration 0.9.13 to 1.0.0

### ISSUE THREAD

**Issue by ChristianCOMMARMOND** [MysticRyuujin/guac-install#76]
On centos 7, with a 0.9.13 installed using this script: https://github.com/ROBERTPASCAL/guacamole/blob/master/guacamole-install-script.sh

Upgrade seems to go seamlessly, but then, guacamole shows an blank web page (the html is not empty and still write 0.9.13).

After analysis:
Directory /etc/guacamole/extensions and /etc/guacamole/lib are not created (for me, they exist in /var/lib).

guacamole.war was not replaced in /usr/share/tomcat, webapps points to /var/lib/tomcat/webapps, which contains a link guacamole.war which point to /var/lib/guacamole/guacamole.war
But, it looks like the new 1.0.0 guacamole.war is in /etc/guacamole/guacamole.war

So, I changed this link to points to the new /etc/guacamole/guacamole.war

Now, I get the login screen 1.0.0. but I cannot login, because guacamole does not connect to mysql...

Then, I copied mysql-connector from /var/lib/guacamole/lib to /etc/guacamole/lib (and removed the directory /var/lib/guacamole).

I deleted all occurrences of 0.9.13 directories and files.

But still not working...

And then, I discovered, that the new GUACAMOLE_HOME, which is supposed to be /etc/guacamole is just a joke. 
I had to create a symlink from /etc/guacamole to /var/lib/guacamole, else, guacamole did not even try to read the configuration file, and don't dream about connecting to the database.

So, the script is a good help for those who installed guacamole with the listed script. But still a lot of things to do.

And I am afraid that this installation will still be difficult to maintain, because of the choices done by this script writters. (But I thank them, since I could use guacamole thanks to their job).

And I thank you too, because, even if I lost a few hours getting it to work, it made me take the step.

But then, it seems that this version is worse than the one I used...

Still super slow, and I see guacamole unable to use the CPU. The server is still at a few percents of CPU even if I open 5 remote sessions. 
The more session, the slower it is, but still, no memory (700M when the server has 2gb) nor CPU is used.
So I may have to go back to the old version...

Christian

**Comment by Neustradamus** [comment]
@MysticRyuujin, @ChristianCOMMARMOND, @ROBERTPASCAL: Any news?

**Comment by thimslugga** [comment]
It's not entirely clear too me, did you install using one script from a different repo and then another script from this repo to upgrade your installation to 1.0.0?

**Comment by MysticRyuujin** [comment]
I'm closing this due to 1.1.0 changes, also my upgrade script works with my install script...not with other people's install scripts. Since they're doing things differently, the upgrade process is different too...
