### ISSUE TITLE
guac-upgrade.sh fails in Debian 9, wrong path for guacamole.war

### ISSUE THREAD

**Issue by MagicFab** [MysticRyuujin/guac-install#77]
Many thanks for your work on this script!

I initially installed Guacamole 9.14 in Debian 9 with steps which I have documented [here](https://wiki.debian.org/Guacamole).

When reviewing the script I noticed it copied the guacamole.war file to `/etc/guacamole/` (line 90) instead of `/var/lib/${TOMCAT}/webapps/` (`/var/lib/tomcat8/webapps/` in Debian 9).

After executing it when loading the Guacamole home page it was blank.

Replacing line 90 with this resulted in a succesful upgrade:
`mv guacamole-${GUACVERSION}.war /var/lib/${TOMCAT}/webapps/guacamole.war`

I am not sure if this is particular to Debian, may I suggest detecting where guacamole.war is and using that path ?

**Comment by enira** [comment]
Line 248 links it to the correct folder: 
```
ln -s /etc/guacamole/guacamole.war /var/lib/${TOMCAT}/webapps/
```

**Comment by MysticRyuujin** [comment]
I assume this is no longer an issue?

**Comment by enira** [comment]
Tested commit https://github.com/MysticRyuujin/guac-install/commit/c2be2966a52b79000b39fdb05e02e35c6bbf0abd 

On Debian 9 it works without issues, Debian 10 and Debian 8 are suffering from other issues, nit the original ticket owner but I think this can be closed
