### ISSUE TITLE
Successful upgrade from 0.9.14 to 1.0.0  

### ISSUE THREAD

**Issue by raufis27** [MysticRyuujin/guac-install#78]
Just upgraded to 1.0 using upgrade script. Thank you!

**Comment by m4xx75** [comment]
It's not an issue ...

**Comment by joosept** [comment]
Yes, this not an issue, but i will use this thread to say thank Yoy very much for the author of the upgrade script! :)
I was able to upgrade my 0.9.13 version to 1.0.0!
