### ISSUE TITLE
Change URL of Guacamole

### ISSUE THREAD

**Issue by nwf00** [MysticRyuujin/guac-install#79]
Hi all,

Sorry to ask but I'm new user of Guacamole. Is there a way to change the the URL of guacamole? , ex:

https://ipadress/guacamole/#/
https://ipadress/newname/#/

Thanks

**Comment by enira** [comment]
This scrip makes a link from the war so a new link would work, or remove and recreate the symbolic link. 

ln -s /etc/guacamole/guacamole.war /var/lib/${TOMCAT}/webapps/newname.war

If you need it at the URL root, you name it ROOT.war. 

(untested)
