### ISSUE TITLE
How do I uninstall the whole thing?

### ISSUE THREAD

**Issue by UNlDAN** [MysticRyuujin/guac-install#82]
I opened the wrong SSH window and installed it on my DNS server. The DNS server does not have any incoming ports opened to the world, but it's there for no reason. Can someone suggest a way to uninstall this? Thank you

**Comment by gr01d** [comment]
Please provide uninstall option.

**Comment by MysticRyuujin** [comment]
I'm not going to write an uninstall script because there's way too many variables.

When running apt install, it ignores already installed software packages, so I can't just uninstall every package referenced in the script. Those packages may have already been installed, or something else you've installed later are relying on them.

You'll have to manually figure out what packages you want removed and remove them.

I assume that at a minimum you can just uninstall tomcat and call it a day.

**Comment by KMouratidis** [comment]
Indeed you probably can't uninstall all the packages (bash scripts for installations suck) unless you kept track of which were installed or you're willing to parse ugly logs, but here's what a starting place:

1. Search the logs for installed packages. I can't parse this easily but you can probably find some you might want to remove.
```
~$  grep install /var/log/dpkg.log
2020-12-03 06:31:17 status installed linux-modules-5.4.0-53-generic:amd64 5.4.0-53.59
2020-12-03 06:31:17 status half-installed linux-modules-5.4.0-53-generic:amd64 5.4.0-53.59
2020-12-03 19:30:59 install m4:amd64 <none> 1.4.18-4
2020-12-03 19:30:59 status half-installed m4:amd64 1.4.18-4
2020-12-03 19:30:59 status triggers-pending install-info:amd64 6.7.0.dfsg.2-
....
2020-12-03 19:31:48 status installed libavcodec58:amd64 7:4.2.4-1ubuntu0.1
2020-12-03 19:31:48 status installed libmount-dev:amd64 2.34-0.1ubuntu9.1
2020-12-03 19:31:48 status installed libchromaprint1:amd64 1.4.3-3build1 
```
2. Stop any running services (e.g. `systemctl disable guacd.service` or something & `systemctl daemon-reload`). `top`, `netstat`, `systemctl` and `service --status-all` or similar tools will help with this.
3. Remove any "guac" files **with care**. First run a few `find`s and if you're satisfied run some `rm`s, e.g.:
```
find / -iwholename '*guac*'

################ DANGER #########################
# BE CAREFUL NOT TO DELETE SOMETHING YOU CARE ABOUT #
#################DANGER ########################
find /usr -iwholename '*guac*' -exec rm {} \;
find /etc -iwholename '*guac*' -exec rm {} \;
```

**Comment by gr01d** [comment]
Maybe you can write the uninstall for the guacd package only, disregard the other apt installed or show some info on what has been installed with guacamole (dependencies) so the user have to uninstall them themselves.
