### ISSUE TITLE
Configuration for Azure AD Application proxy

### ISSUE THREAD

**Issue by lprousseau** [MysticRyuujin/guac-install#87]
The script works perfectly, thanks!

I'm trying to secure the access by using Azure AD Application Proxy so I can use Azure AD identity, conditional access, MFA, etc.  When configured I can definitely access the Guacamole server without any problems but when I launch an RDP session, it freezes or become so slow that it's impossible to do anything.  I don't have this problem from the local network or when accessing outside of Application proxy.
Since application proxy settings are limited, I guess I'm missing something with the tomcat configuration.  Any hint would be appreciated. Thanks!

**Comment by Marcus-James-Adams** [comment]
@lprousseau I'm looking at setting up authentication myself this way, did yu get any further with it.   If you don't mind sharing how you have configured it so far. I'm happy to take a look.

**Comment by lprousseau** [comment]
@Marcus-James-Adams seems that RDP sessions on HMTL5 this is still not supported by AAD app proxy.  Hopefully, this will be working soon. (Marked as Planned on MS uservoice)
https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/33918046-support-remote-desktop-web-client-html5-on-azure-a
I beleive the problems is not in the GUAC configuration itself but in the AAD App proxy connector...
