### ISSUE TITLE
Debian 10 Buster compatibility

### ISSUE THREAD

**Issue by Neustradamus** [MysticRyuujin/guac-install#95]
It is possible to have the Debian 10 Buster compatibility?

6 Months since Debian 10 Buster release:
- https://www.debian.org/News/2019/20190706

One year already since Guacamole 1.0.0: Latest release: 1.0.0 (released on 2019-01-08 19:42:00 -0800)
- https://guacamole.apache.org/

Thanks in advance.

**Comment by MysticRyuujin** [comment]
Do you know what library changes I need to make? I can add support if you know what the names of the libraries are.

**Comment by MysticRyuujin** [comment]
Should be fixed with #107
