### ISSUE TITLE
Upgrade Guac 1.1.0

### ISSUE THREAD

**Issue by pablopol24** [MysticRyuujin/guac-install#96]
Hi, updating Guac 1.0 to 1.1 stops connecting with customers. any ideas?

**Comment by SoulSeekkor** [comment]
Created a pull request https://github.com/MysticRyuujin/guac-install/pull/97.

1.1 uses a different freerdp package causing it to break on upgrade.

**Comment by pablopol24** [comment]
the update works perfectly with the new script !!!
