### ISSUE TITLE
trouble with TOTP

### ISSUE THREAD

**Issue by postheimer** [MysticRyuujin/guac-install#98]
Hello , i have try your script for installing guac on debian 10 buster

all is ok but i have one problem with TOTP 

when i disable TOTP the username - password match and all is good 

but when i active totp , the username/password match and after scan the qr code on google authentificator , i said the message  authentification failed on webpage

but when i log to log i have authentification sucess ... 

i have made a ntp server , because i suspect a problem with the clock but same problem

i have search several hour i have no find a issue

**Comment by MysticRyuujin** [comment]
@postheimer for Guacamole support I suggest you reach out to the developers. This isn't an issue with the script for installation.
